-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local item_text = { -- [id] = { page1, page2 (optional), page3 (optional), ... }
[20545] = { -- Decoded Twilight Text (1 page)
[===[Для негайного розповсюдження серед усіх членів Сутінкового Молота.

Враховуючи поточний стан справ в Силітусі, будь-яке розповсюдження текстів "Правовірного" повинно відбуватися у супроводі не менше, ніж двох озброєних членів Сутінкового Молота.

Будь-які члени організації, які порушать цей наказ, будуть суворо покарані.

— Сутінковий лорд Д'Сак]===],
},
}

if addonTable.item_text then
    for k, v in pairs(item_text) do addonTable.item_text[k] = v end
else
    addonTable.item_text = item_text
end
