-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local object_text = { -- [name] = { page1, page2 (optional), ... }, or a list of namesakes { { pages..., h1=hash of the english page 1 }, ... }
}

if addonTable.object_text then
    for k, v in pairs(object_text) do addonTable.object_text[k] = v end
else
    addonTable.object_text = object_text
end
