-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local chat = { -- [npc_name_en] = { [1] = npc_name_uk (optional), [code1] = text1, [code2] = text2, ... }
["!common"] = {
-- Alright I'm going! Stop yelling!
["aimgsytimgoi"] = [===[Гаразд, йду я! Не кричи!]===],
-- For the Horde!
["fththehorde_"] = [===[За Орду!]===],
-- I'll crush you!
["ilcyrushyou_"] = [===[Я тебе розчавлю!]===],
-- Just release me already! I've had enough!
["jrmaivheasem"] = [===[Та відпусти вже мене! З мене досить!]===],
-- Me smash! You die!
["msydashyoudi"] = [===[Я бити! Ти вмирати!]===],
-- Make yourself useful and help me out here!
["myuahmohself"] = [===[Зроби хоч щось корисне і допоможи мені!]===],
-- %s attempts to run away in fear!
["satraiftstor"] = [===[%s налякано тікає геть!]===],
-- %s becomes enraged!
["sbecomesenra"] = [===[%s лютує!]===],
-- %s calls for help!
["scfhlsforhel"] = [===[%s кличе на допомогу!]===],
-- %s charges!
["scharges____"] = [===[%s стрімко атакує!]===],
-- %s dies.
["sdies_______"] = [===[%s вмирає.]===],
-- %s laughs.
["slaughs_____"] = [===[%s сміється.]===],
-- %s sighs.
["ssighs______"] = [===[%s зітхає.]===],
-- This better be the last one!
["tbbtlotterbe"] = [===[Сподіваюсь, це останній!]===],
-- What? You mean you can't kill this one by yourself?
["wymyctktobyy"] = [===[Що? Хочеш сказати, що не зможеш вбити його самостійно?]===],
-- You better back me up on this one!
["ybbmuotorbac"] = [===[Краще допоможи мені!]===],
},
["Majordomo Executus"] = { "мажордом Екзекутус",
-- Ashes to ashes!
["ataestoashes"] = [===[Прах до праху.]===],
-- Behold Ragnaros - the Firelord! He who was ancient when this world was young! Bow before him, mortals! Bow before your ending!
["bybbhmbbyeww"] = [===[Готуйтесь зустрітися з Раґнаросом - Повелителем Вогню! Тим, хто був древнім, ще в часи юності цього світу! Схиліться перед ним, смертні! Схиліться перед своєю загибеллю!]===],
-- Brashly, you have come to wrest the secrets of the Living Flame! You will soon regret the recklessness of your quest.
["bywsrtroyqlf"] = [===[Ви прийшли, щоб зухвало викрасти таємниці Живого Полум'я! Незабаром ви пошкодуєте про свою необачність.]===],
-- Impossible! Stay your attack, mortals... I submit! I submit!
["isyamisisest"] = [===[Це неможливо! Зупиніться, смертні... Я здаюсь! Здаюсь!]===],
-- Impudent whelps! You've rushed headlong to your own deaths! See now, the master stirs!\r\n
["itmsrntyodsn"] = [===[Нахабні виродки! Ви кинулися стрімголов назустріч власній смерті! Готуйтесь, бо володар прокинувся!]===],
-- I go now to summon the lord whose house this is. Should you seek an audience with him, your paltry lives will surely be forfeit! Nevertheless, seek out his lair, if you dare!
["iybfnsohliyd"] = [===[А тепер я покличу володаря цієї обителі. Аудієнція з ним, безсумнівно, буде останньою у вашому житті! Що ж, ходіть до його лігва, якщо наважитеся!]===],
-- Reckless mortals! None may challenge the Sons of the Living flame!
["rmnmctsotlft"] = [===[Безрозсудні смертні! Ніхто не сміє кидати виклик Синам Живого Полум'я!]===],
-- The runes of warding have been destroyed! Hunt down the infidels, my brethren!
["tbowhbdhdtim"] = [===[Захисні руни знищено! Вбийте невірних, брати мої!]===],
-- These mortal infidels, my lord! They have invaded your sanctum and seek to steal your secrets!
["ttsysthiysas"] = [===[Ці невірні смертні, мій повелителю! Вони вдерлися в твою обитель і прагнуть викрасти твої таємниці!]===],
},
["Myra Tyrngaarde"] = { "Міра Тірнґаард",
-- Come get yer fresh bread!
["cgyfbetyerfr"] = [===[Підходьте по свіжий хліб!]===],
-- Fresh bread, baked this very morning.
["fbbtvmreadba"] = [===[Свіжий хліб, спечений цього ранку.]===],
-- Fresh bread for sale!
["fbfshbreadfo"] = [===[Продається свіжий хліб!]===],
},
["Ragnaros"] = { "Раґнарос",
-- BY FIRE BE PURGED!
["bfbprebepurg"] = [===[ВОГОНЬ ОЧИСТИТЬ ВАС!]===],
-- COME FORTH, MY SERVANTS! DEFEND YOUR MASTER!
["cfmsdymthmys"] = [===[СЮДИ, МОЇ СЛУГИ! ЗАХИСТІТЬ СВОГО ПОВЕЛИТЕЛЯ!]===],
-- DIE, INSECT!
["dieinsect___"] = [===[ЗДОХНИ, КОМАХО!]===],
-- FOOL! YOU ALLOWED THESE INSECTS TO RUN RAMPANT THROUGH THE HALLOWED CORE? AND NOW YOU LEAD THEM TO MY VERY LAIR? YOU HAVE FAILED ME, EXECUTUS! JUSTICE SHALL BE MET, INDEED!
["fafmejsbmiyh"] = [===[ДУРЕНЬ! ТИ ДОЗВОЛИВ ЦИМ КОМАХАМ РОЗГУЛЮВАТИ ПО СВЯЩЕННОМУ ЯДРУ? І ТЕПЕР ТИ ПРИВІВ ЇХ ДО МОГО ЛІГВА? ТИ ПІДВІВ МЕНЕ, ЕКЗЕКУТУС! І ТИ ОТРИМАЄШ СПРАВЕДЛИВЕ ПОКАРАННЯ!]===],
-- NOW FOR YOU, INSECTS! BOLDLY, YOU SOUGHT THE POWER OF RAGNAROS. NOW YOU SHALL SEE IT FIRSTHAND!\r\n
["nyssifrnporn"] = [===[А ВИ, КОМАХИ! ВИ ПРАГНУЛИ СИЛИ РАГНАРОСА. ТЕПЕР ВИ ВІДЧУЄТЕ ЇЇ НА ВЛАСНІЙ ШКУРІ!]===],
-- Ragnaros has withdrawn to the elemental plane.
["rhwttepshasw"] = [===[Рагнарос відійшов у вимір стихій.]===],
-- TOO SOON! YOU HAVE AWAKENED ME TOO SOON, EXECUTUS! WHAT IS THE MEANING OF THIS INTRUSION???
["tmotimtsewit"] = [===[ЗАНАДТО РАНО! ТИ РОЗБУДИВ МЕНЕ ЗАНАДТО РАНО, ЕКЗЕКУТУС! ЩО ВСЕ ЦЕ ОЗНАЧАЄ?]===],
-- TASTE THE FLAMES OF SULFURON!
["ttfostheflam"] = [===[СКУШТУЙТЕ ПОЛУМ'Я СУЛЬФУРОНА!]===],
-- YOU CANNOT DEFEAT THE LIVING FLAME!
["ycdtlfnotdef"] = [===[ВАМ НЕ ЗДОЛАТИ ЖИВЕ ПОЛУМ'Я!]===],
},
["Thrall"] = { "Тралл",
-- Be bathed in my power! Drink in my might! Battle for the glory of the Horde!
["bgothdimmbft"] = [===[Купайтеся в моїй силі! Сповнюйтесь моєю могутністю! Бийтеся за славу Орди!]===],
-- Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen!
["habhfmhetfwr"] = [===[Шануймо наших героїв! Цього дня вони завдали нищівного удару одному з наших найненависніших ворогів! Фальшивий вождь, Ренд Чорнорук, нарешті мертвий!]===],
},
}

if addonTable.chat then
    for k, v in pairs(chat) do
        if type(addonTable.chat[k]) == "table" and type(v) == "table" then
            for vk, vv in pairs(v) do
                addonTable.chat[k][vk] = vv
            end
        else
            addonTable.chat[k] = v
        end
    end
else
    addonTable.chat = chat
end
