-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local gossip = { -- [npc_id] = { [code1] = text1, [code2] = text2, ... }
["!common"] = {
-- Auction House
["ahctionhouse"] = [===[Аукціонний дім]===],
-- Bank
["bank________"] = [===[Банк]===],
-- Battlemaster
["battlemaster"] = [===[Воєначальник]===],
-- Class Trainer
["ctasstrainer"] = [===[Класовий тренер]===],
-- Guild Master
["gmildmaster_"] = [===[Розпорядник гільдій]===],
-- Gryphon Master
["gmyphonmaste"] = [===[Приборкувач грифонів]===],
-- How do I form a guild?
["hdifagformag"] = [===[Як створити гільдію?]===],
-- I am interested in mage training.
["iaiittereste"] = [===[Мене цікавить тренування мага.]===],
-- Inn
["inn_________"] = [===[Таверна]===],
-- I want to browse your goods.
["iwtbygobrows"] = [===[Я хочу переглянути ваші товари.]===],
-- I want to create a guild crest.
["iwtcagccreat"] = [===[Я хочу створити герб гільдії.]===],
-- I wish to untrain my pet.
["iwtumpountra"] = [===[Я хочу скасувати навчання свого вихованця.]===],
-- I wish to unlearn my talents.
["iwtumtounlea"] = [===[Я хочу забути свої таланти.]===],
-- Let me browse your goods.
["lmbygbrowsey"] = [===[Дозвольте мені переглянути ваші товари.]===],
-- Make this inn your home.
["mtiyhhisinny"] = [===[Зупинитися в цій таверні.]===],
-- Please teach me.
["ptmaseteachm"] = [===[Будь ласка, навчіть мене.]===],
-- Profession Trainer
["ptofessiontr"] = [===[Тренер професій]===],
-- Rut'theran Ferry
["rtftheranfer"] = [===[Рут'Теранська переправа]===],
-- Stable Master
["smablemaster"] = [===[Доглядач стайні]===],
-- Tell me about dungeons I could explore.
["tmadiceboutd"] = [===[Розкажіть мені про підземелля, які я міг би відвідати.]===],
-- Train me.
["tmainme_____"] = [===[Навчіть мене.]===],
-- Train me in the ways of the beast.
["tmitwotbnthe"] = [===[Навчіть мене шляхам звіра.]===],
-- What can I do at an inn?
["wcidaaiidoat"] = [===[Чим я можу зайнятися в таверні?]===],
-- Weapon Master
["wmaponmaster"] = [===[Знавець зброї]===],
-- Wind Rider Master
["wrmdridermas"] = [===[Приборкувач виверн]===],
-- Weapons Trainer
["wtaponstrain"] = [===[Тренер володіння зброєю]===],
-- Where would you like to fly to?
["wwyltftuldyo"] = [===[Куди бажаєш полетіти?]===],
-- Yes. I do.
["yidido______"] = [===[Так, хочу.]===],
},
[197] = { -- Marshal McBride
-- Hey, citizen!  You look like a stout one.  We guards are spread a little thin out here, and I could use your help...
["haltohaicuyh"] = [===[Гей, {стать:громадянине:громадянко}! Виглядаєте {стать:міцним:міцною}. Нас, охоронців, тут небагато, і мені потрібна ваша допомога...]===],
},
[198] = { -- Khelden Bremen
-- Greetings <class>.  Shall I provide you with further insight into the world of magic?
["gmipywfiitwo"] = [===[Вітаю, {клас:к}. Чи варто мені глибше розповісти тобі про світ магії?]===],
-- Well met, <class>.  My advice to you is this: as you travel the world, be wary of magic for it will burn the untrained.
["wwbwomfiwbtu"] = [===[Вітаю, {клас:к}. Моя порада тобі: подорожуючи світом, остерігайся магії, бо вона спалить непідготовленого.]===],
},
[375] = { -- Priestess Anetta
-- Do not turn your back on the Light, <class>, it may be the one thing that saves you some day.
["dottsysdimbt"] = [===[Не повертайся спиною до світла, {клас:к}, можливо це єдине, що колись тебе врятує.]===],
-- I trust the Light is with you, <name>. Is there something that I can I help you with?
["icihywyitsti"] = [===[Я вірю, що Світло з тобою, {ім'я:к}. Чи можу я чимось тобі допомогти?]===],
},
[911] = { -- Llane Beshere
-- I can tell just by the way you're standing that you're no warrior.
--
-- Why don't you go do something safe, like read a book.
["irrabtygdssl"] = [===[Я бачу, що ти не {стать:воїн:воїтелька}, просто по тому як ти стоїш.

Чому б тобі не зайнятися чимось безпечним, наприклад почитати книжку.]===],
-- Stormwind is the pillar of the human race, maintained through strength of will and the edge of the sturdy blade.
["sateotsbtsow"] = [===[Штормовій — опора людської раси, яка підтримується силою волі та вістрям міцного клинка.]===],
},
[925] = { -- Brother Sammuel
-- May the Light protect you this day.
["mtlpytdightp"] = [===[Нехай Світло береже тебе.]===],
},
}

if addonTable.gossip then
    for k, v in pairs(gossip) do
        if type(addonTable.gossip[k]) == "table" and type(v) == "table" then
            for vk, vv in pairs(v) do
                addonTable.gossip[k][vk] = vv
            end
        else
            addonTable.gossip[k] = v
        end
    end
else
    addonTable.gossip = gossip
end
