-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local item_text = { -- [id] = { page1, page2 (optional), page3 (optional), ... }
}

if addonTable.item_text then
    for k, v in pairs(item_text) do addonTable.item_text[k] = v end
else
    addonTable.item_text = item_text
end
