-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local chat = { -- [npc_name_en] = { [1] = npc_name_uk (optional), [code1] = text1, [code2] = text2, ... }
["High Tinker Mekkatorque"] = { "Верховний штукар Меккакруть",
-- Citizens of the great cities of both Gnomeregan and Ironforge, gather round and take heed! This mighty adventurer has done the impossible and ended the threat of Sicco Thermaplugg once and for all and has saved Dun Morogh from a fiery fate! Gather and be inspired, one and all!
["cgdshfioaa"] = [===[Мешканці великих міст Гномреґану та Залізогарту, збирайтеся та слухайте! Цей могутній шукач пригод зробив неможливе, раз і назавжди поклав край загрозі Сіко Термоштепселя й врятував Дун-Морог від страшної долі! Збирайтеся і надихайтеся, всі без винятку!]===],
},
}

if addonTable.chat then
    for k, v in pairs(chat) do
        if type(addonTable.chat[k]) == "table" and type(v) == "table" then
            for vk, vv in pairs(v) do
                addonTable.chat[k][vk] = vv
            end
        else
            addonTable.chat[k] = v
        end
    end
else
    addonTable.chat = chat
end
