-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local npc = { -- [id] = { title, description (optional) }
[184383] = { "Сульфурон Провісник", en="Sulfuron Harbinger" }, -- Sulfuron Harbinger
[185320] = { "нестабільний хроматичний дракон", en="Unstable Chromatic Drake" }, -- Unstable Chromatic Drake
[201722] = { "Гаму-ра", en="Ghamoo-ra" }, -- Ghamoo-ra
[201854] = { "Різзак", en="Cutty" }, -- Cutty
[202060] = { "заморожений мурлок", en="Frozen Murloc" }, -- Frozen Murloc
[202079] = { "тіньовий марник", en="Shadowfiend" }, -- Shadowfiend
[202093] = { "споліморфлений учень", en="Polymorphed Apprentice" }, -- Polymorphed Apprentice
[202116] = { "головоріз-грабіжник", en="Cut-throat Mugger" }, -- Cut-throat Mugger
[202699] = { "барон Акваніс", en="Baron Aquanis" }, -- Baron Aquanis
[202838] = { "елементаль глибин", en="Fathom Elemental" }, -- Fathom Elemental
[202839] = { "елементаль бистрини", en="Riptide Elemental" }, -- Riptide Elemental
[202840] = { "елементаль потоку", en="Torrent Elemental" }, -- Torrent Elemental
[203079] = { "мандрівний мечник", en="Wandering Swordsman" }, -- Wandering Swordsman
[203138] = { "розпорядник Лютого Ковадла", en="Anvilrage Overseer" }, -- Anvilrage Overseer
[203139] = { "син Аруґала", en="Son of Arugal" }, -- Son of Arugal
[203218] = { "величезний вир", en="Giant Whirlpool" }, -- Giant Whirlpool
[203226] = { "Вікторія Вудс", "мисливиця на чудовиськ", en="Viktoria Woods" }, -- Viktoria Woods <Monster Hunter>
[203475] = { "Лів Бредфорд", "барменка", en="Liv Bradford" }, -- Liv Bradford <Bartender>
[203478] = { "Стюарт", en="Stuart" }, -- Stuart
[204068] = { "леді Сарвесс", en="Lady Sarevess" }, -- Lady Sarevess
[204070] = { "Собоз", en="Soboz" }, -- Soboz
[204091] = { "гвардієць Чорноводдя", en="Blackfathom Elite" }, -- Blackfathom Elite
[204256] = { "Дем'єн Кейн", "посередник душ", en="Damien Kane" }, -- Damien Kane <Soul Broker>
[204503] = { "мертвий послушник", en="Dead Acolyte" }, -- Dead Acolyte
[204645] = { "гвардієць Чорноводдя", en="Blackfathom Elite" }, -- Blackfathom Elite
[204827] = { "рештки шукача пригод", en="Adventurer's Remains" }, -- Adventurer's Remains
[204921] = { "Ґеліхаст", en="Gelihast" }, -- Gelihast
[204937] = { "дух шукача пригод", en="Adventurer's Spirit" }, -- Adventurer's Spirit
[204989] = { "поранений шукач пригод", en="Wounded Adventurer" }, -- Wounded Adventurer
[205153] = { "Ада Ґельгардт", en="Ada Gelhardt" }, -- Ada Gelhardt
[205278] = { "брат Ромул", en="Brother Romulus" }, -- Brother Romulus
[205382] = { "Моква", en="Mokwa" }, -- Mokwa
[205635] = { "Такода Сонячна Грива", "натуралістка", en="Takoda Sunmane" }, -- Takoda Sunmane
[205692] = { "шелесткий кущ", en="Rustling Bush" }, -- Rustling Bush
[205700] = { "браконьєр ТзНБ \"Авантюра\"", en="Venture Co. Poacher" }, -- Venture Co. Poacher
[205724] = { "мацак Чорноводдя", en="Blackfathom Tendril" }, -- Blackfathom Tendril
[205729] = { "Бортон Тінистий Тотем", "тренер пройдисвітів?", en="Boarton Shadetotem" }, -- Boarton Shadetotem
[206245] = { "вивільнений дух природи", en="Unleashed Nature Spirit" }, -- Unleashed Nature Spirit
[206248] = { "дерев'яна статуя", en="Wooden Effigy" }, -- Wooden Effigy
[207356] = { "Лорґус Джетт", en="Lorgus Jett" }, -- Lorgus Jett
[207358] = { "жриця припливу Чорноводних глибин", en="Blackfathom Tide Priestess" }, -- Blackfathom Tide Priestess
[207359] = { "жриця припливу Чорноводних глибин", en="Blackfathom Tide Priestess" }, -- Blackfathom Tide Priestess
[207367] = { "жриця припливу Чорноводних глибин", en="Blackfathom Tide Priestess" }, -- Blackfathom Tide Priestess
[207397] = { "осквернений тотем буревію", en="Corrupted Windfury Totem" }, -- Corrupted Windfury Totem
[207457] = { "осквернений тотем щита блискавки", en="Corrupted Lightning Shield Totem" }, -- Corrupted Lightning Shield Totem
[207515] = { "Сховогрив", en="Lurkmane" }, -- Lurkmane
[207576] = { "осквернений тотем розплавленої люті", en="Corrupted Molten Fury Totem" }, -- Corrupted Molten Fury Totem
[207577] = { "місячний камінь", en="Lunar Stone" }, -- Lunar Stone
[207637] = { "Ватейя Дерев'яне Копито", "мисливиця на чудовиськ", en="Vateya Timberhoof" }, -- Vateya Timberhoof <Monster Hunter>
[207743] = { "Неталі Гордий Вітер", "товари загального вжитку", en="Netali Proudwind" }, -- Netali Proudwind <General Goods>
[207754] = { "Муарт", en="Mooart" }, -- Mooart
[207795] = { "гальванічний символ", en="Galvanic Icon" }, -- Galvanic Icon
[207957] = { "Вагі Кісткощеп", "мисливиця на чудовиськ", en="Vahi Bonesplitter" }, -- Vahi Bonesplitter <Monster Hunter>
[208023] = { "Ґру'арк", en="Gru'ark" }, -- Gru'ark
[208036] = { "Ба'со", en="Ba'so" }, -- Ba'so
[208071] = { "грабіжник з завулка", en="Back-alley Mugger" }, -- Back-alley Mugger
[208124] = { "Ралук", en="Raluk" }, -- Raluk
[208179] = { "шелесткий кущ", en="Rustling Bush" }, -- Rustling Bush
[208180] = { "бритвогривий браконьєр", en="Razormane Poacher" }, -- Razormane Poacher
[208184] = { "Раззіль", "заклинач змій", en="Razzil" }, -- Razzil
[208196] = { "Жабрик", en="Gillgar" }, -- Gillgar
[208226] = { "Дармак Кривавий Вий", "посередник душ", en="Darmak Bloodhowl" }, -- Darmak Bloodhowl <Soul Broker>
[208275] = { "заморожений макрура", en="Frozen Makrura" }, -- Frozen Makrura
[208307] = { "лоа змій", en="Serpent Loa" }, -- Serpent Loa
[208309] = { "вівтар лоа", en="Loa Altar" }, -- Loa Altar
[208518] = { "Ґаєріан", en="Gaeriyan" }, -- Gaeriyan
[208565] = { "вівтар Світла", en="Altar of the Light" }, -- Altar of the Light
[208619] = { "Дорак Могиль", "хірург-тактик", en="Dorac Graves" }, -- Dorac Graves
[208638] = { "Фьоді", en="Fyodi" }, -- Fyodi
[208652] = { "Джунні Сталехід", "мисливиця на чудовиськ", en="Junni Steelpass" }, -- Junni Steelpass <Monster Hunter>
[208682] = { "Дентон Хмуроступ", "посередник душ", en="Denton Bleakway" }, -- Denton Bleakway <Soul Broker>
[208711] = { "Тобі", en="Toby" }, -- Toby
[208712] = { "дивний кавун", en="Odd Melon" }, -- Odd Melon
[208752] = { "заморожений трог", en="Frozen Trogg" }, -- Frozen Trogg
[208802] = { "поранений шукач пригод", en="Wounded Adventurer" }, -- Wounded Adventurer
[208812] = { "Йорул", en="Jorul" }, -- Jorul
[208875] = { "грабіжник з завулка", en="Back-alley Mugger" }, -- Back-alley Mugger
[208876] = { "головоріз-грабіжник", en="Cut-throat Mugger" }, -- Cut-throat Mugger
[208886] = { "Чорнощур", en="Blackrat" }, -- Blackrat
[208919] = { "Блакитносерд", en="Blueheart" }, -- Blueheart
[208920] = { "Пенні Гокінс", "барменка", en="Penny Hawkins" }, -- Penny Hawkins <Bartender>
[208927] = { "мертвий послушник", en="Dead Acolyte" }, -- Dead Acolyte
[208975] = { "шелесткий кущ", en="Rustling Bush" }, -- Rustling Bush
[209002] = { "Ґаклік Пустокрут", "посередник душ", en="Gaklik Voidtwist" }, -- Gaklik Voidtwist <Soul Broker>
[209004] = { "Бруарт", en="Bruart" }, -- Bruart
[209209] = { "гвардієць Чорноводдя", en="Blackfathom Elite" }, -- Blackfathom Elite
[209214] = { "мурлок Чорноводдя", en="Blackfathom Murloc" }, -- Blackfathom Murloc
[209511] = { "дитинча оазисного тріскощелепа", en="Oasis Snapjaw Hatchling" }, -- Oasis Snapjaw Hatchling
[209524] = { "дозорний гепард", en="Patrolling Cheetah" }, -- Patrolling Cheetah
[209548] = { "таємний агент", en="Secret Agent" }, -- Secret Agent
[209607] = { "лейтенант Камневар", en="Lieutenant Stonebrew" }, -- Lieutenant Stonebrew
[209608] = { "Дельвіна", "мисливиця на чудовиськ", en="Delwynna" }, -- Delwynna <Monster Hunter>
[209678] = { "сутінковий лорд Келріс", en="Twilight Lord Kelris" }, -- Twilight Lord Kelris
[209742] = { "міраж пустелі", en="Desert Mirage" }, -- Desert Mirage
[209758] = { "загарбницький кошмар", en="Invading Nightmare" }, -- Invading Nightmare
[209797] = { "Брууз", en="Bruuz" }, -- Bruuz
[209811] = { "шелесткий кущ", en="Rustling Bush" }, -- Rustling Bush
[209812] = { "браконьєр Гнилого Кореня", en="Fallenroot Poacher" }, -- Fallenroot Poacher
[209815] = { "примарна жриця", en="Phantasmal Priestess" }, -- Phantasmal Priestess
[209872] = { "Силларт", en="Syllart" }, -- Syllart
[209889] = { "Голокіст", "продавець PvP-спорядження", en="Barebones" }, -- Barebones
[209908] = { "єретичний ідол", en="Heretic Idol" }, -- Heretic Idol
[209928] = { "Моуг", en="Mowgh" }, -- Mowgh
[209948] = { "Релерон", "доглядач", en="Relaeron" }, -- Relaeron <Caretaker>
[209949] = { "хворий олень", en="Sickly Deer" }, -- Sickly Deer
[209954] = { "рештки демона", en="Demonic Remains" }, -- Demonic Remains
[209958] = { "Ґрайкс", en="Graix" }, -- Graix
[210107] = { "Хрустун", en="Kackle" }, -- Kackle
[210451] = { "леді Седоракс", en="Lady Sedorax" }, -- Lady Sedorax
[210482] = { "Пакснозз", en="Paxnozz" }, -- Paxnozz
[210483] = { "агресивний чавлик", en="Aggressive Squashling" }, -- Aggressive Squashling
[210487] = { "жах з глибин", en="Horror of the Deep" }, -- Horror of the Deep
[210501] = { "прототип жнивального збирача", en="Harvest Reaper Prototype" }, -- Harvest Reaper Prototype
[210533] = { "Срібногін", en="Silverspur" }, -- Silverspur
[210537] = { "невмирущий робітник", en="Undying Laborer" }, -- Undying Laborer
[210549] = { "розвідник повстанців", en="Defias Scout" }, -- Defias Scout
[210697] = { "капітан Нам'єр", en="Captain Namier" }, -- Captain Namier
[210750] = { "М'ґррґл", en="M'grrgl" }, -- M'grrgl
[210802] = { "оплутана жертва", en="Webbed Victim" }, -- Webbed Victim
[210845] = { "Джиксо Ракетосхиб", "шибайголова-любитель", en="Jixo Madrocket" }, -- Jixo Madrocket
[210887] = { "довірливий гордокрил", en="Unsuspecting Pridewing" }, -- Unsuspecting Pridewing
[210995] = { "Алонсо", "мандрівний лицар", en="Alonso" }, -- Alonso
[211022] = { "Оуен Тедд", "бібліотекар", en="Owen Thadd" }, -- Owen Thadd <Librarian>
[211033] = { "Ґаріон Венделл", "бібліотекар", en="Garion Wendell" }, -- Garion Wendell <Librarian>
[211042] = { "дитинча зеленого дракона", en="Green Dragon Whelp" }, -- Green Dragon Whelp
[211146] = { "загублена шукачка пригод", en="Lost Adventurer" }, -- Lost Adventurer
[211183] = { "таємний агент", en="Secret Agent" }, -- Secret Agent
[211188] = { "Метра Вуглесерда", en="Maethra Slagheart" }, -- Maethra Slagheart
[211200] = { "Аґон", en="Agon" }, -- Agon
[211225] = { "Баж'ура", en="Baj'ura" }, -- Baj'ura
[211229] = { "Дітріх Прайс", en="Dietrich Praice" }, -- Dietrich Praice
[211269] = { "викликаний світлик", en="Summoned Wisp" }, -- Summoned Wisp
[211279] = { "осквернений дух звіра", en="Corrupt Spirit Beast" }, -- Corrupt Spirit Beast
[211298] = { "Сірноя", en="Syrnoya" }, -- Syrnoya
[211330] = { "підозріла ціль", en="Suspicious Target" }, -- Suspicious Target
[211338] = { "мисливець Злобного Плавника", en="Vile Fin Hunter" }, -- Vile Fin Hunter
[211653] = { "Ґріззбі", en="Grizzby" }, -- Grizzby
[211736] = { "посивілий захисник", en="Grizzled Protector" }, -- Grizzled Protector
[211764] = { "Ґефелл", en="Gefell" }, -- Gefell
[211765] = { "Ґемела", en="Gemela" }, -- Gemela
[211875] = { "елементаль гнилі", en="Decayed Elemental" }, -- Decayed Elemental
[211951] = { "Коартул", en="Koartul" }, -- Koartul
[211965] = { "Карродин", en="Carrodin" }, -- Carrodin
[212159] = { "старий Серра'кіс", "виїдений" }, -- Old Serra'kis
[212186] = { "Ґрюґімдерн", en="Grugimdern" }, -- Grugimdern
[212209] = { "Водяник", en="Vodyanoi" }, -- Vodyanoi
[212261] = { "пробуджений ліч", en="Awakened Lich" }, -- Awakened Lich
[212334] = { "мертвий культист Сутінкового Молота", en="Dead Twilight Cultist" }, -- Dead Twilight Cultist
[212458] = { "примарний панцирник", en="Phantasmal Crustacean" }, -- Phantasmal Crustacean
[212461] = { "примарний слуга", en="Phantasmal Servant" }, -- Phantasmal Servant
[212462] = { "примарний панцирошкур", en="Phantasmal Softshell" }, -- Phantasmal Softshell
[212463] = { "примарний тріскощелеп", en="Phantasmal Snapjaw" }, -- Phantasmal Snapjaw
[212598] = { "Реке Ґріннес", en="Recke Grinnes" }, -- Recke Grinnes
[212692] = { "закований елементаль", en="Bound Elemental" }, -- Bound Elemental
[212694] = { "Гірзек", en="Hirzek" }, -- Hirzek
[212699] = { "лучниця Срібнокрилих", en="Silverwing Archer" }, -- Silverwing Archer
[212703] = { "дріада Срібнокрилих", en="Silverwing Dryad" }, -- Silverwing Dryad
[212706] = { "друїд Срібнокрилих", en="Silverwing Druid" }, -- Silverwing Druid
[212707] = { "Лародар", "хранитель гаю", en="Larodar" }, -- Larodar <Keeper of the Grove>
[212727] = { "бугай Пісні Війни", en="Warsong Grunt" }, -- Warsong Grunt
[212728] = { "рейдер Пісні Війни", en="Warsong Raider" }, -- Warsong Raider
[212729] = { "шаман Пісні Війни", en="Warsong Shaman" }, -- Warsong Shaman
[212730] = { "Тояра", "майстриня клинка", en="Tojara" }, -- Tojara <Blademaster>
[212753] = { "закатована душа", en="Tortured Soul" }, -- Tortured Soul
[212763] = { "садистський марник", en="Sadistic Fiend" }, -- Sadistic Fiend
[212801] = { "Джубей", "майстер клинка", en="Jubei" }, -- Jubei <Blademaster>
[212802] = { "Муґул Хитрий", "майстер клинка", en="Moogul the Sly" }, -- Moogul the Sly <Blademaster>
[212803] = { "Цередвин", "хранитель гаю", en="Ceredwyn" }, -- Ceredwyn <Keeper of the Grove>
[212804] = { "Центрій", "хранитель гаю", en="Centrius" }, -- Centrius <Keeper of the Grove>
[212809] = { "стогнучий дух", en="Wailing Spirit" }, -- Wailing Spirit
[212837] = { "первісна аномалія", en="Primordial Anomaly" }, -- Primordial Anomaly
[212969] = { "Казраґор", "провидець", en="Kazragore" }, -- Kazragore
[212970] = { "Фелора Місячне Проміння", "жриця місяця", en="Felore Moonray" }, -- Felore Moonray
[213077] = { "Елейн Комптон", "офіцерка постачань", en="Elaine Compton" }, -- Elaine Compton <Supply Officer>
[213334] = { "Аку'май", en="Aku'mai" }, -- Aku'mai
[213444] = { "таємничий мандрівник", en="Mysterious Traveler" }, -- Mysterious Traveler
[213445] = { "Рашель Андер", en="Raszel Ander" }, -- Raszel Ander
[213451] = { "елементаль очищення", en="Cleansing Elemental" }, -- Cleansing Elemental
[213540] = { "таємничий мандрівник", en="Mysterious Traveler" }, -- Mysterious Traveler
[213708] = { "гончак Легіона", en="Legion Hound" }, -- Legion Hound
[213709] = { "бичувальниця Маннорока", en="Mannoroc Lasher" }, -- Mannoroc Lasher
[213710] = { "вартовий скверни", en="felguard" }, -- felguard
[213711] = { "опаляючий пекельник", en="Searing Infernal" }, -- Searing Infernal
[213795] = { "Ґаррік", en="Gharrik" }, -- Gharrik
[213994] = { "їдка крапля", en="Corrosive Droplet" }, -- Corrosive Droplet
[214070] = { "Джорна", "офіцерка постачань", en="Jornah" }, -- Jornah <Supply Officer>
[214096] = { "Докімі", "офіцерка постачань", en="Dokimi" }, -- Dokimi <Supply Officer>
[214098] = { "Ґіша", "офіцерка постачань", en="Gishah" }, -- Gishah <Supply Officer>
[214099] = { "Тамелін Олдрідж", "офіцерка постачань", en="Tamelyn Aldridge" }, -- Tamelyn Aldridge <Supply Officer>
[214101] = { "Марсі Бейкер", "офіцерка постачань", en="Marcy Baker" }, -- Marcy Baker <Supply Officer>
[214129] = { "легкий подрібнювач ТзНБ \"Авантюра\"", en="Venture Co. Light Shredder" }, -- Venture Co. Light Shredder
[214208] = { "Н'ора Сердечна", "дослідниця екзотичної фауни", en="N'ora Anyheart" }, -- N'ora Anyheart
[214212] = { "загадкова постать", en="Shadowy Figure" }, -- Shadowy Figure
[214456] = { "Дро'зем Богохульний", en="Dro'zem the Blasphemous" }, -- Dro'zem the Blasphemous
[214519] = { "спалювач Ґар'ім", en="Incinerator Gar'im" }, -- Incinerator Gar'im
[214529] = { "сміливець Кам'яний Смолоскип", en="Brave Stonetorch" }, -- Brave Stonetorch
[214530] = { "Ардель Дральта", en="Ardelle Dralta" }, -- Ardelle Dralta
[214603] = { "жриця припливу Чорноводних глибин", en="Blackfathom Tide Priestess" }, -- Blackfathom Tide Priestess
[214612] = { "рибоїд Аку'май", en="Aku'mai Fisher" }, -- Aku'mai Fisher
[214695] = { "наймит", en="peon" }, -- peon
[214876] = { "Давій Пустосяй", en="Davius Voidstar" }, -- Davius Voidstar
[214954] = { "Рікс Ксіззікс", "бюро знахідок", en="Rix Xizzix" }, -- Rix Xizzix
[215062] = { "молільник", en="Supplicant" }, -- Supplicant
[215072] = { "вівтар лоа", en="Loa Altar" }, -- Loa Altar
[215081] = { "лоа-кажан", en="Bat Loa" }, -- Bat Loa
[215095] = { "молільник", en="Supplicant" }, -- Supplicant
[215096] = { "молільник", en="Supplicant" }, -- Supplicant
[215098] = { "молільник", en="Supplicant" }, -- Supplicant
[215108] = { "тріскощелеп Аку'май", en="Aku'mai Snapjaw" }, -- Aku'mai Snapjaw
[215367] = { "світанковий вартовий Селґорм", "Сріблястий Світанок", en="Dawnwatcher Selgorm" }, -- Dawnwatcher Selgorm <The Argent Dawn>
[215369] = { "Башана Рунний Тотем", en="Bashana Runetotem" }, -- Bashana Runetotem
[215643] = { "Токал", en="Tokal" }, -- Tokal
[215655] = { "Ілларі Сутінкове Перо", en="Illari Duskfeather" }, -- Illari Duskfeather
[215728] = { "пробійник натовпу 9-60", en="Crowd Pummeler 9-60" }, -- Crowd Pummeler 9-60
[215849] = { "Доан Карган", en="Doan Karhan" }, -- Doan Karhan
[215850] = { "Рашель Андер", en="Raszel Ander" }, -- Raszel Ander
[215854] = { "тінев'яз-послушник", en="Shadowbinder Acolyte" }, -- Shadowbinder Acolyte
[215855] = { "тінев'яз-послушник", en="Shadowbinder Acolyte" }, -- Shadowbinder Acolyte
[215974] = { "Дес'Алтек", en="Des'Altek" }, -- Des'Altek
[216289] = { "Орокай", en="Orokai" }, -- Orokai
[216310] = { "гнилий древній", en="Rotting Ancient" }, -- Rotting Ancient
[216437] = { "саджанець древня", en="Ancient Sapling" }, -- Ancient Sapling
[216445] = { "саджанець древня", en="Ancient Sapling" }, -- Ancient Sapling
[216448] = { "саджанець древня", en="Ancient Sapling" }, -- Ancient Sapling
[216451] = { "саджанець древня", en="Ancient Sapling" }, -- Ancient Sapling
[216463] = { "Айлґра Розколотий Бивень", "матір штормів" }, -- Ailgrha Splittusk
[216474] = { "руйнівна буря", en="Ravaging Tempest" }, -- Ravaging Tempest
[216659] = { "сатир Гнилого Кореня", en="Fallenroot Satyr" }, -- Fallenroot Satyr
[216660] = { "пройдисвіт Гнилого Кореня", en="Fallenroot Rogue" }, -- Fallenroot Rogue
[216661] = { "жриця припливу Чорноводних глибин", en="Blackfathom Tide Priestess" }, -- Blackfathom Tide Priestess
[216662] = { "оракул Чорноводдя", en="Blackfathom Oracle" }, -- Blackfathom Oracle
[216664] = { "Спрок", "загублена команда", en="Sprok" }, -- Sprok
[216665] = { "гномреґанський біженець", en="Gnomeregan Evacuee" }, -- Gnomeregan Evacuee
[216666] = { "Техбот", en="Techbot" }, -- Techbot
[216667] = { "божевільний лепрогном", en="Addled Leper" }, -- Addled Leper
[216668] = { "опромінений загарбник", en="Irradiated Invader" }, -- Irradiated Invader
[216669] = { "печерний грабіжник", en="Caverndeep Pillager" }, -- Caverndeep Pillager
[216670] = { "печерний здобичник", en="Caverndeep Looter" }, -- Caverndeep Looter
[216671] = { "печерний загарбник", en="Caverndeep Invader" }, -- Caverndeep Invader
[216672] = { "Намдо Справошип", "інженерні припаси", en="Namdo Bizzfizzle" }, -- Namdo Bizzfizzle <Engineering Supplies>
[216810] = { "всохлий викид", en="Desiccated Fallout" }, -- Desiccated Fallout
[216854] = { "виверна Розкутого Вітру", en="Freewind Post Wyvern" }, -- Freewind Post Wyvern
[216902] = { "Хотайн Злотодзвін", "Пасовища Димного Лісу", en="Wulmort Jinglepocket" }, -- Wulmort Jinglepocket <Smokywood Pastures>
[216915] = { "дивний сніговик", en="Strange Snowman" }, -- Strange Snowman
[216924] = { "Якоб Хапмідяк", "Пасовища Димного Лісу", en="Kaymard Copperpinch" }, -- Kaymard Copperpinch <Smokywood Pastures>
[216931] = { "Мерзенний Ґрінч", en="The Abominable Greench" }, -- The Abominable Greench
[216937] = { "Джубей", "майстер клинка", en="Jubei" }, -- Jubei <Blademaster>
[217049] = { "дзеркальне відображення", "майстер клинка", en="Mirror Image" }, -- Mirror Image <Blademaster>
[217280] = { "Бубонник", en="Grubbis" }, -- Grubbis
[217290] = { "огрський блискавковідвід", en="Ogre Lightning Rod" }, -- Ogre Lightning Rod
[217300] = { "Товкач", "кухар-аматор", en="Skonk" }, -- Skonk
[217302] = { "Там'кар", en="Tam'kar" }, -- Tam'kar
[217305] = { "древній вогняний елементаль", en="Ancient Fire Elemental" }, -- Ancient Fire Elemental
[217308] = { "радіоактивний слиз", en="Irradiated Goo" }, -- Irradiated Goo
[217387] = { "брат Аттик", en="Brother Atticus" }, -- Brother Atticus
[217392] = { "вогнегляд Дубелен", en="Flameseer Dubelen" }, -- Flameseer Dubelen
[217412] = { "Амаріліс Вебб", en="Amaryllis Webb" }, -- Amaryllis Webb
[217418] = { "Зай'енкі", en="Zai'enki" }, -- Zai'enki
[217580] = { "спокусниця Кейна", "володарка бажань", en="Seductress Ceeyna" }, -- Seductress Ceeyna
[217582] = { "печерний душитель", en="Caverndeep Ambusher" }, -- Caverndeep Ambusher
[217588] = { "деревний тарантул", en="Arbor Tarantula" }, -- Arbor Tarantula
[217589] = { "сінний довгоносик", en="Hay Weevil" }, -- Hay Weevil
[217590] = { "плотокус", en="Flesh Picker" }, -- Flesh Picker
[217605] = { "шукач Порожнечі", en="Void Seeker" }, -- Void Seeker
[217620] = { "безрозсудний чорнокнижник", en="Reckless Warlock" }, -- Reckless Warlock
[217669] = { "обпалена крикнява пройдисвітка", en="Scorched Screeching Roguefeather" }, -- Scorched Screeching Roguefeather
[217689] = { "Зірі \"Мутра\" Дрібноверт", "Техноманка", en="Ziri \"The Wrench\" Littlesprocket" }, -- Ziri "The Wrench" Littlesprocket
[217703] = { "обпалений консорт Високого Сідала", en="Singed Highperch Consort" }, -- Singed Highperch Consort
[217706] = { "Казраґор", "провидець", en="Kazragore" }, -- Kazragore
[217707] = { "Фелора Місячне Проміння", "жриця місяця", en="Felore Moonray" }, -- Felore Moonray
[217711] = { "обпалена шипова пума", en="Seared Needles Cougar" }, -- Seared Needles Cougar
[217733] = { "печерний грабіжник", en="Caverndeep Pillager" }, -- Caverndeep Pillager
[217783] = { "партизан Кровоскальпих", en="Bloodscalp Guerrilla" }, -- Bloodscalp Guerrilla
[217836] = { "Шипозуб", en="Needletooth" }, -- Needletooth
[217908] = { "добровільна жертва", en="Willing Sacrifice" }, -- Willing Sacrifice
[217945] = { "одомашнена бойова курка", en="Domesticated Attack Chicken" }, -- Domesticated Attack Chicken
[217956] = { "Чавкун", en="Chomper" }, -- Chomper
[217957] = { "вбитий член Багряного Походу", en="Slain Scarlet Crusader" }, -- Slain Scarlet Crusader
[217969] = { "підривниця Емі Куций Запал", en="Blastmaster Emi Shortfuse" }, -- Blastmaster Emi Shortfuse
[217996] = { "Еонас", "колишній паладин Сріблястої Десниці", en="Aeonas" }, -- Aeonas
[218019] = { "бойовий манекен", en="Combat Dummy" }, -- Combat Dummy
[218020] = { "бойовий манекен", en="Combat Dummy" }, -- Combat Dummy
[218021] = { "бойовий манекен", en="Combat Dummy" }, -- Combat Dummy
[218029] = { "чемпіон Зів'ялої Кори", en="Witherbark Champion" }, -- Witherbark Champion
[218032] = { "голіаф Зів'ялої Кори", en="Witherbark Goliath" }, -- Witherbark Goliath
[218115] = { "Май'зін", "торговець кров'ю з племені Ґурубаші", en="Mai'zin" }, -- Mai'zin
[218160] = { "Еонас Виправданий", "колишній паладин Сріблястої Десниці" }, -- Aeonas
[218229] = { "капітан Аранзас", en="Captain Aransas" }, -- Captain Aransas
[218230] = { "Вендель Матерс", en="Wendel Mathers" }, -- Wendel Mathers
[218237] = { "Вірдал Дивоверт", "біженці Гномреґана", en="Wirdal Wondergear" }, -- Wirdal Wondergear
[218240] = { "автоматичний захисний механізм", en="Tower Defense Automaton" }, -- Tower Defense Automaton
[218241] = { "загадкова постать", en="Shadowy Figure" }, -- Shadowy Figure
[218242] = { "СТХ-04/ЧД", en="STX-04/BD" }, -- STX-04/BD
[218243] = { "СТХ-13/БН", en="STX-13/LL" }, -- STX-13/LL
[218244] = { "СТХ-25/БК", en="STX-25/NB" }, -- STX-25/NB
[218245] = { "СТХ-37/КК", en="STX-37/CN" }, -- STX-37/CN
[218246] = { "Ґурґток", en="Gurgthock" }, -- Gurgthock
[218249] = { "слизькоріза жриця припливу", en="Slitherblade Tide Priestess" }, -- Slitherblade Tide Priestess
[218273] = { "мандрівний мечник", en="Wandering Swordsman" }, -- Wandering Swordsman
[218344] = { "вибухове яйце", en="Explosive Egg" }, -- Explosive Egg
[218349] = { "ходяча бомба", en="Walking Bomb" }, -- Walking Bomb
[218537] = { "мекженер Термоштепсель" }, -- Sicco Thermaplugg
[218538] = { "СТХ-96/ВГ", en="STX-96/FR" }, -- STX-96/FR
[218571] = { "Тінь Ераніка" }, -- Eranikus
[218606] = { "неповороткий сновидець", en="Lumbering Dreamwalker" }, -- Lumbering Dreamwalker
[218624] = { "Атал'аларіон", "вартовий ідола", en="Atal'alarion" }, -- Atal'alarion
[218690] = { "Ха'даму", "обранець лоа крові", en="Kha'damu" }, -- Kha'damu
[218718] = { "Оґом Злиденний", en="Ogom the Wretched" }, -- Ogom the Wretched
[218721] = { "Джаммал'ан-Пророк", en="Jammal'an the Prophet" }, -- Jammal'an the Prophet
[218819] = { "гнійний гнилеслиз", en="Festering Rotslime" }, -- Festering Rotslime
[218868] = { "Міджан", en="Mijan" }, -- Mijan
[218869] = { "мертвоголова геомантка", en="Death's Head Geomancer" }, -- Death's Head Geomancer
[218870] = { "мертвоголова некромантка", en="Death's Head Necromancer" }, -- Death's Head Necromancer
[218871] = { "мертвоголова культистка", en="Death's Head Cultist" }, -- Death's Head Cultist
[218873] = { "мертвоголовий воїн", en="Death's Head Warrior" }, -- Death's Head Warrior
[218891] = { "скелетний слуга", en="Skeletal Servant" }, -- Skeletal Servant
[218908] = { "вбивця Багряного Походу", en="Scarlet Crusade Assassin" }, -- Scarlet Crusade Assassin
[218920] = { "даларанський агент", "Лілове око", en="Dalaran Agent" }, -- Dalaran Agent
[218922] = { "Гукку", en="Hukku" }, -- Hukku
[218931] = { "темний вершник", en="Dark Rider" }, -- Dark Rider
[218970] = { "СТХ-97/КГ", en="STX-97/IC" }, -- STX-97/IC
[218972] = { "СТХ-98/РА", en="STX-98/PO" }, -- STX-98/PO
[218974] = { "СТХ-99/УМ", en="STX-99/XD" }, -- STX-99/XD
[219110] = { "вогняна бомба", en="Incendiary Bomb" }, -- Incendiary Bomb
[219111] = { "крижана бомба", en="Frost Bomb" }, -- Frost Bomb
[219112] = { "радіоактивна бомба", en="Radioactive Bomb" }, -- Radioactive Bomb
[219177] = { "Омен", en="Omen" }, -- Omen
[219199] = { "прислужник Омена" }, -- Omen
[219659] = { "Верховний штукар Меккакруть", "король гномів" }, -- Gelbin Mekkatorque
[219663] = { "Ноґґ", "інженер-експерт", en="Nogg" }, -- Nogg <Expert Engineer>
[219822] = { "прикутий дух", en="Chained Spirit" }, -- Chained Spirit
[219986] = { "дух вовка", en="Spirit Wolf" }, -- Spirit Wolf
[220007] = { "в'язкі відходи", en="Viscous Fallout" }, -- Viscous Fallout
[220072] = { "Електрошокер 6000", en="Electrocutioner 6000" }, -- Electrocutioner 6000
[220076] = { "знахар Зум'ра", en="Witch Doctor Zum'rah" }, -- Witch Doctor Zum'rah
[220142] = { "Титанзілла", en="Titanzilla" }, -- Titanzilla
[220170] = { "король Кулак", en="King Knuckles" }, -- King Knuckles
[220174] = { "Гамма-Ра", en="Gamma-Ra" }, -- Gamma-Ra
[220178] = { "Птеродан", en="Pterodan" }, -- Pterodan
[220179] = { "Мекатрон", en="Mekatron" }, -- Mekatron
[220396] = { "варевний ловець Зул'Фаррака", en="Zul'Farrak Concoction Stalker" }, -- Zul'Farrak Concoction Stalker
[220833] = { "Жнець Сну", en="Dreamscythe" }, -- Dreamscythe
[220864] = { "Ткач", en="Weaver" }, -- Weaver
[220930] = { "Фрікс Ксіззікс", en="Frix Xizzix" }, -- Frix Xizzix
[220942] = { "кошмар", en="Nightmare" }, -- Nightmare
[220984] = { "Фіцбуц Мітрил", en="Fizbuz Mithril" }, -- Fizbuz Mithril
[221165] = { "канатолаз", en="Rope Climber" }, -- Rope Climber
[221168] = { "зловісний вовк-альфа", en="Dire Wolf Alpha" }, -- Dire Wolf Alpha
[221169] = { "чорна вдова-мати виводка", en="Black Widow Broodmother" }, -- Black Widow Broodmother
[221170] = { "викорчований морокодрев", en="Uprooted Gloomwood" }, -- Uprooted Gloomwood
[221171] = { "бігун кошмару", en="Nightmare Runner" }, -- Nightmare Runner
[221172] = { "ткач кошмару", en="Nightmare Weaver" }, -- Nightmare Weaver
[221173] = { "зшитий патрульний", "черговий подарунок від Бальзамувальника", en="Stitched Patroller" }, -- Stitched Patroller
[221174] = { "навіжений огр", en="Deranged Ogre" }, -- Deranged Ogre
[221175] = { "божевільний вогнеткач", en="Demented Fire Weaver" }, -- Demented Fire Weaver
[221176] = { "дракончик нічного жаху", en="Nightterror Whelp" }, -- Nightterror Whelp
[221200] = { "драконіда-жахоступ", en="Wyrmkin Terrorwalker" }, -- Wyrmkin Terrorwalker
[221201] = { "канатолаз", en="Rope Climber" }, -- Rope Climber
[221204] = { "Ілантрій", en="Ylanthrius" }, -- Ylanthrius
[221206] = { "Вварк'Зул", "король лісу", en="Vvarc'Zul" }, -- Vvarc'Zul
[221207] = { "Амокарок", "вожак зграї", en="Amokarok" }, -- Amokarok
[221210] = { "Кролл Тінь Гори", "друїд Пазура", en="Kroll Mountainshade" }, -- Kroll Mountainshade <Druid of the Claw>
[221215] = { "Алара Цілителька Рощі", "друїд Пазура", en="Alara Grovemender" }, -- Alara Grovemender <Druid of the Claw>
[221216] = { "Еленора Болотоступ", "друїд Пазура", en="Elenora Marshwalker" }, -- Elenora Marshwalker <Druid of the Claw>
[221220] = { "вартова сну Амалія", en="Dreamwarden Amalia" }, -- Dreamwarden Amalia
[221221] = { "вартовий сну Дорілар", en="Dreamwarden Dorilar" }, -- Dreamwarden Dorilar
[221222] = { "вартовий сну Талінар", en="Dreamwarden Thalinar" }, -- Dreamwarden Thalinar
[221223] = { "смеркоклин-тінелов", en="Duskblaze Shadowstalker" }, -- Duskblaze Shadowstalker
[221226] = { "біс-палій", en="Firestarter Imp" }, -- Firestarter Imp
[221227] = { "гончак кошмару", en="Nightmare Hound" }, -- Nightmare Hound
[221230] = { "гризлі кошмару", en="Nightmare Grizzly" }, -- Nightmare Grizzly
[221257] = { "олень-смерторіг", en="Deathhorn Stag" }, -- Deathhorn Stag
[221258] = { "шиполов сну", en="Dreamthorn Stalker" }, -- Dreamthorn Stalker
[221259] = { "драконіда-ночелов", en="Wyrmkin Nightstalker" }, -- Wyrmkin Nightstalker
[221260] = { "дракончик жаху", en="Terror Whelp" }, -- Terror Whelp
[221261] = { "зрадник Полум'яного Сну", en="Dreamfire Betrayer" }, -- Dreamfire Betrayer
[221262] = { "пеклоклик Полум'яного Сну", en="Dreamfire Hellcaller" }, -- Dreamfire Hellcaller
[221263] = { "мстивий древній", en="Vengeful Ancient" }, -- Vengeful Ancient
[221264] = { "жнець сну", en="Dreamharvester" }, -- Dreamharvester
[221265] = { "Ларсера", en="Larsera" }, -- Larsera
[221266] = { "Залій", "старійшина Полум'яного Сну", en="Zalius" }, -- Zalius
[221267] = { "Подрібнювач 9000", en="Shredder 9000" }, -- Shredder 9000
[221268] = { "Доран Гілка Сну", "друїд Пазура", en="Doran Dreambough" }, -- Doran Dreambough <Druid of the Claw>
[221269] = { "Масеара Осінній Місяць", "друїд Пазура", en="Maseara Autumnmoon" }, -- Maseara Autumnmoon <Druid of the Claw>
[221270] = { "Аліссіан Вітрозов", "друїд Пазура", en="Alyssian Windcaller" }, -- Alyssian Windcaller <Druid of the Claw>
[221271] = { "вартовий сну Еллодар", en="Dreamwarden Ellodar" }, -- Dreamwarden Ellodar
[221272] = { "вартовий сну Мандоран", en="Dreamwarden Mandoran" }, -- Dreamwarden Mandoran
[221273] = { "вартова сну Ланарія", en="Dreamwarden Lanaria" }, -- Dreamwarden Lanaria
[221282] = { "сноклят Іскристого Жару", en="Emberspark Dreamsworn" }, -- Emberspark Dreamsworn
[221283] = { "біс Вогнища Сну", en="Dreampyre Imp" }, -- Dreampyre Imp
[221292] = { "гончак-мисливець Сну", en="Dreamhunter Hound" }, -- Dreamhunter Hound
[221312] = { "жахоперий гіпогриф", en="Dreadfeather Hippogryph" }, -- Dreadfeather Hippogryph
[221315] = { "нестабільний світлик", en="Unstable Wisp" }, -- Unstable Wisp
[221324] = { "розбитий горем грифон", en="Grief-Crazed Gryphon" }, -- Grief-Crazed Gryphon
[221325] = { "драконіда-зоряна мисливиця", en="Wyrmkin Starhunter" }, -- Wyrmkin Starhunter
[221326] = { "дракончик гніву", en="Wrath Whelp" }, -- Wrath Whelp
[221328] = { "міцнохват Водяного Сну", en="Dreamwater Vicejaw" }, -- Dreamwater Vicejaw
[221329] = { "гідра-мисливиця Сну", en="Dreamhunter Hydra" }, -- Dreamhunter Hydra
[221330] = { "полеглий місячний совух", en="Fallen Moonkin" }, -- Fallen Moonkin
[221331] = { "Флорій", en="Florius" }, -- Florius
[221333] = { "згубний совух", en="Doomkin" }, -- Doomkin
[221334] = { "Гаму-Раджа", en="Ghamoo-Raja" }, -- Ghamoo-Raja
[221335] = { "Еліанар Тінепивця", "друїд Пазура", en="Elianar Shadowdrinker" }, -- Elianar Shadowdrinker <Druid of the Claw>
[221336] = { "Серліна Яскрава Зоря", "друїд Пазура", en="Serlina Starbright" }, -- Serlina Starbright <Druid of the Claw>
[221337] = { "Веанна Захмарний Сон", "друїд Пазура", en="Veanna Cloudsleeper" }, -- Veanna Cloudsleeper <Druid of the Claw>
[221351] = { "вартова сну Валорі", en="Dreamwarden Valori" }, -- Dreamwarden Valori
[221352] = { "вартова сну Санатель", en="Dreamwarden Sanathel" }, -- Dreamwarden Sanathel
[221353] = { "вартовий сну Ланінар", en="Dreamwarden Laninar" }, -- Dreamwarden Laninar
[221356] = { "зореклят Згубної Іскри", en="Doomspark Starsworn" }, -- Doomspark Starsworn
[221357] = { "біс Зорепилу", en="Stardust Imp" }, -- Stardust Imp
[221360] = { "гончак-зоряний вбивця", en="Starkiller Hound" }, -- Starkiller Hound
[221361] = { "божевільний райдужний дракончик", en="Mad Sprite" }, -- Mad Sprite
[221364] = { "несамовита химера", en="Rampaging Chimaera" }, -- Rampaging Chimaera
[221365] = { "хляскун Смертельної Пелюстки", en="Deathpetal Lasher" }, -- Deathpetal Lasher
[221367] = { "драконід-берсерк", en="Wyrmkin Berserker" }, -- Wyrmkin Berserker
[221369] = { "несамовитий дракончик", en="Frenzied Whelp" }, -- Frenzied Whelp
[221370] = { "оперена пройдисвітка Джерельного Сну", en="Dreamspring Roguefeather" }, -- Dreamspring Roguefeather
[221371] = { "бурезовка Джерельного Сну", en="Dreamspring Stormcaller" }, -- Dreamspring Stormcaller
[221373] = { "розлючений гірський велетень", en="Enraged Mountain Giant" }, -- Enraged Mountain Giant
[221375] = { "загублена донька", en="Lost Daughter" }, -- Lost Daughter
[221377] = { "мстивий син", en="Vengeful Son" }, -- Vengeful Son
[221389] = { "Алондрій", "хранитель кошмару", en="Alondrius" }, -- Alondrius
[221391] = { "Слірена", "королева гарпій", en="Slirena" }, -- Slirena
[221393] = { "Тиранікус", en="Tyrannikus" }, -- Tyrannikus
[221394] = { "аватар Гаккара" }, -- Hakkar
[221395] = { "Мелліас Землеглад", "друїд Пазура", en="Mellias Earthtender" }, -- Mellias Earthtender <Druid of the Claw>
[221396] = { "хранитель крові Гаккарі", en="Hakkari Bloodkeeper" }, -- Hakkari Bloodkeeper
[221398] = { "Нерен Піснеплин", "друїд Пазура", en="Nerene Brooksinger" }, -- Nerene Brooksinger <Druid of the Claw>
[221399] = { "Жамнісс Цілителька Дерев", "друїд Пазура", en="Jamniss Treemender" }, -- Jamniss Treemender <Druid of the Claw>
[221400] = { "Каджинд", en="Kajind" }, -- Kajind
[221401] = { "вартовий сну Шелдрін", en="Dreamwarden Sheldryn" }, -- Dreamwarden Sheldryn
[221402] = { "вартовий сну Ґорлас", en="Dreamwarden Gorlas" }, -- Dreamwarden Gorlas
[221404] = { "вартова сну Анадель", en="Dreamwarden Anadelle" }, -- Dreamwarden Anadelle
[221406] = { "місяцеступ-зрадник", en="Moonwalker Betrayer" }, -- Moonwalker Betrayer
[221407] = { "біс Тіньового Сну", en="Dreamshadow Imp" }, -- Dreamshadow Imp
[221408] = { "нічний мисливець", en="Night Hunter" }, -- Night Hunter
[221426] = { "ритуаліст Атал'ай", en="Atal'ai Ritualist" }, -- Atal'ai Ritualist
[221471] = { "польовий командир Паландар", en="Field Captain Palandar" }, -- Field Captain Palandar
[221472] = { "розвідниця Чарла", en="Scout Charla" }, -- Scout Charla
[221477] = { "польовий командир Ганнала", en="Field Captain Hannalah" }, -- Field Captain Hannalah
[221479] = { "польовий командир Корліан", en="Field Captain Korlian" }, -- Field Captain Korlian
[221480] = { "польовий командир Аруннель", en="Field Captain Arunnel" }, -- Field Captain Arunnel
[221482] = { "розвідник Ґемерон", en="Scout Gemeron" }, -- Scout Gemeron
[221483] = { "розвідниця Фаллія", en="Scout Fallia" }, -- Scout Fallia
[221484] = { "розвідник Тандрос", en="Scout Thandros" }, -- Scout Thandros
[221575] = { "Елрік", en="Elrick" }, -- Elrick
[221587] = { "Еонас Виправданий", "колишній паладин Сріблястої Десниці" }, -- Aeonas
[221636] = { "Грегорі", "Правдоносець", en="Gregory" }, -- Gregory
[221637] = { "Ґешер", en="Gasher" }, -- Gasher
[221638] = { "Лоро", en="Loro" }, -- Loro
[221639] = { "Золо", en="Zolo" }, -- Zolo
[221640] = { "Зул'Лор", en="Zul'Lor" }, -- Zul'Lor
[221651] = { "Керулеос", en="Ceruleos" }, -- Ceruleos
[221656] = { "суворий завсідник", en="Stern-faced Bar Patron" }, -- Stern-faced Bar Patron
[221740] = { "Калефактус Вивільнений", en="Calefactus the Unleashed" }, -- Calefactus the Unleashed
[221759] = { "Ґешер", en="Gasher" }, -- Gasher
[221761] = { "Гаккар", en="Hakkar" }, -- Hakkar
[221762] = { "Гаккар", en="Hakkar" }, -- Hakkar
[221827] = { "магістр Фалат", "емісар оселі Квел'Даніл", en="Magister Falath" }, -- Magister Falath
[221828] = { "мстивий дух", en="Vengeful Spirit" }, -- Vengeful Spirit
[221829] = { "Каджинд", "чемпіон арени" }, -- Kajind
[221830] = { "мандрівний мечник", en="Wandering Swordsman" }, -- Wandering Swordsman
[221831] = { "Ґос Мастилоляп", en="Gos Greasebasher" }, -- Gos Greasebasher
[221832] = { "скакун Сріблястої Десниці", en="Silver Hand Charger" }, -- Silver Hand Charger
[221833] = { "Гукку", en="Hukku" }, -- Hukku
[221834] = { "Лоро", en="Loro" }, -- Loro
[221835] = { "Міджан", en="Mijan" }, -- Mijan
[221836] = { "Золо", en="Zolo" }, -- Zolo
[221837] = { "Зул'Лор", en="Zul'Lor" }, -- Zul'Lor
[221924] = { "Казказ Нечистий", en="Kazkaz the Unholy" }, -- Kazkaz the Unholy
[221928] = { "аватар гіпогрифа", en="Hippogryph Avatar" }, -- Hippogryph Avatar
[221933] = { "аватар місячного совуха", en="Moonkin Avatar" }, -- Moonkin Avatar
[221935] = { "аватар дереваня", en="Treant Avatar" }, -- Treant Avatar
[221942] = { "Морфаз", en="Morphaz" }, -- Morphaz
[221943] = { "Хаззас", en="Hazzas" }, -- Hazzas
[221985] = { "Тирісій", en="Tyrisius" }, -- Tyrisius
[222004] = { "осквернений помірний прояв води", en="Corrupt Moderate Manifestation of Water" }, -- Corrupt Moderate Manifestation of Water
[222005] = { "помірний прояв води", en="Moderate Manifestation of Water" }, -- Moderate Manifestation of Water
[222008] = { "канатолаз", en="Rope Climber" }, -- Rope Climber
[222044] = { "сутінковий темний шаман", en="Twilight Dark Shaman" }, -- Twilight Dark Shaman
[222052] = { "біс-дослідник", en="Explorer Imp" }, -- Explorer Imp
[222088] = { "драконеня кошмару", en="Nightmare Whelpling" }, -- Nightmare Whelpling
[222089] = { "лускоклят кошмару", en="Nightmare Scalebane" }, -- Nightmare Scalebane
[222188] = { "загадкова постать", en="Shadowy Figure" }, -- Shadowy Figure
[222192] = { "лоза кошмару", en="Nightmare Vine" }, -- Nightmare Vine
[222198] = { "злиття кошмару", en="Nightmare Amalgamation" }, -- Nightmare Amalgamation
[222228] = { "щілина Скверни", en="Fel Sliver" }, -- Fel Sliver
[222232] = { "осквернений помірний прояв повітря", en="Corrupt Moderate Manifestation of Air" }, -- Corrupt Moderate Manifestation of Air
[222233] = { "Охк'зі", en="Ohk'zi" }, -- Ohk'zi
[222243] = { "Зопілот", en="Zopilote" }, -- Zopilote
[222261] = { "Максиміліан \"Мастильник\"", en="Maximillian \"The Greaser\"" }, -- Maximillian "The Greaser"
[222286] = { "Наміда Зловісний Тотем", en="Namida Grimtotem" }, -- Namida Grimtotem
[222288] = { "розлом Скверни", en="Fel Rift" }, -- Fel Rift
[222289] = { "помірний прояв повітря", en="Moderate Manifestation of Air" }, -- Moderate Manifestation of Air
[222290] = { "безталанний шукач пригод", en="Unfortunate Adventurer" }, -- Unfortunate Adventurer
[222316] = { "Шипоскок Мідномот", en="Fizzbizz Coppercoil" }, -- Fizzbizz Coppercoil
[222367] = { "дитинча гроддокської мавпи", en="Groddoc Infant" }, -- Groddoc Infant
[222376] = { "дитинча гроддокської мавпи", en="Groddoc Infant" }, -- Groddoc Infant
[222405] = { "скупчення лей-лінії", en="Leyline Conflux" }, -- Leyline Conflux
[222406] = { "гроддокський матріарх", en="Groddoc Matriarch" }, -- Groddoc Matriarch
[222407] = { "розлючений прояв лей-лінії", en="Enraged Leywalker" }, -- Enraged Leywalker
[222408] = { "емісар Тінезубих", en="Shadowtooth Emissary" }, -- Shadowtooth Emissary
[222409] = { "Бос \"Ґобб\" Злотник", "здобич і знахідки зі Сну", en="Boss \"Gobb\" Goldnick" }, -- Boss "Gobb" Goldnick
[222410] = { "загадкова постать", en="Shadowy Figure" }, -- Shadowy Figure
[222413] = { "дослідник Залґо", "постачальник загублених речей", en="Zalgo the Explorer" }, -- Zalgo the Explorer
[222416] = { "скелетний вітряний змій", en="Skeletal Wind Serpent" }, -- Skeletal Wind Serpent
[222418] = { "верховий кажан", en="Riding Bat" }, -- Riding Bat
[222444] = { "поранений гном", "відомий лицар", en="Injured Gnome" }, -- Injured Gnome
[222451] = { "мурлок-лускотун", en="Itty Bitty Murloc" }, -- Itty Bitty Murloc
[222478] = { "стражниця Келдара Сонцеклин", en="Sentinel Keldara Sunblade" }, -- Sentinel Keldara Sunblade
[222513] = { "дикий росток", en="Wild Growth" }, -- Wild Growth
[222514] = { "кошмарний гриб", en="Nightmare Mushroom" }, -- Nightmare Mushroom
[222516] = { "туман Сну", en="Dream Fog" }, -- Dream Fog
[222519] = { "неврівноважений друїд", en="Unbalanced Druid" }, -- Unbalanced Druid
[222521] = { "камінь Сну", en="Dreamstone" }, -- Dreamstone
[222522] = { "дух Аґамаґґана" }, -- Agamaggan
[222525] = { "патрульний Лютого Ковадла", en="Anvilrage Patrol" }, -- Anvilrage Patrol
[222530] = { "подертий мандрівник", en="Rugged Traveler" }, -- Rugged Traveler
[222531] = { "подертий мандрівник", en="Ragged Traveler" }, -- Ragged Traveler
[222542] = { "барабан Атал'ай", en="Atal'ai Drum" }, -- Atal'ai Drum
[222543] = { "табличка Атал'ай", en="Atal'ai Slab" }, -- Atal'ai Slab
[222544] = { "маска Атал'ай", en="Atal'ai Mask" }, -- Atal'ai Mask
[222545] = { "свічка Атал'ай", en="Atal'ai Candle" }, -- Atal'ai Candle
[222546] = { "Йодакс-Руйнівник", en="Iodax the Obliterator" }, -- Iodax the Obliterator
[222551] = { "Ґрендаґ Яскравобородий", "талановитий дворф", en="Grendag Brightbeard" }, -- Grendag Brightbeard
[222553] = { "мумія Атал'ай", en="Atal'ai Mummy" }, -- Atal'ai Mummy
[222566] = { "живе полум'я", en="Animated Flame" }, -- Animated Flame
[222573] = { "несамовитий древній", en="Delirious Ancient" }, -- Delirious Ancient
[222580] = { "дитя Апа'ро", en="Child of Apa'ro" }, -- Child of Apa'ro
[222617] = { "помірний прояв вогню", en="Moderate Manifestation of Fire" }, -- Moderate Manifestation of Fire
[222620] = { "осквернений помірний прояв вогню", en="Corrupt Moderate Manifestation of Fire" }, -- Corrupt Moderate Manifestation of Fire
[222623] = { "помірний прояв землі", en="Moderate Manifestation of Earth" }, -- Moderate Manifestation of Earth
[222625] = { "осквернений помірний прояв землі", en="Corrupt Moderate Manifestation of Earth" }, -- Corrupt Moderate Manifestation of Earth
[222636] = { "древня святиня", en="Ancient Shrine" }, -- Ancient Shrine
[222647] = { "древній дух", en="Ancient Spirit" }, -- Ancient Spirit
[222648] = { "дика святиня", en="Wild Shrine" }, -- Wild Shrine
[222649] = { "дикий дух", en="Wild Spirit" }, -- Wild Spirit
[222650] = { "вітряна святиня", en="Windswept Shrine" }, -- Windswept Shrine
[222651] = { "вітряний дух", en="Windswept Spirit" }, -- Windswept Spirit
[222656] = { "нічне лезо повстанців", en="Defias Night Blade" }, -- Defias Night Blade
[222684] = { "квартирмейстер Фалінар", en="Quartermaster Falinar" }, -- Quartermaster Falinar
[222685] = { "квартирмейстерка Кайлін", en="Quartermaster Kyleen" }, -- Quartermaster Kyleen
[222686] = { "квартирмейстерка Аландра", en="Quartermaster Alandra" }, -- Quartermaster Alandra
[222687] = { "квартирмейстер Валдейн", en="Quartermaster Valdane" }, -- Quartermaster Valdane
[222689] = { "кровожерливий дух", en="Blood-crazed Spirit" }, -- Blood-crazed Spirit
[222695] = { "маска Миршавого Гілля", en="Vilebranch Mask" }, -- Vilebranch Mask
[222696] = { "тріщина Скверни", en="Fel Crack" }, -- Fel Crack
[222697] = { "розрив Скверни", en="Fel Tear" }, -- Fel Tear
[222698] = { "шрам Скверни", en="Fel Scar" }, -- Fel Scar
[222699] = { "розлючений буревісник", en="Enraged Stormcrow" }, -- Enraged Stormcrow
[222701] = { "купа кісток", en="Pile of Bones" }, -- Pile of Bones
[222702] = { "загублений вбивця", en="Murderous Lost One" }, -- Murderous Lost One
[222703] = { "Шелест Крила", "захисник Азшари", en="Whisperwing" }, -- Whisperwing
[222704] = { "Мудре Перо", "захисник Внутрішніх земель", en="Sagefeather" }, -- Sagefeather
[222705] = { "Трутовик", "захисник Фераласа", en="Blightbark" }, -- Blightbark
[222726] = { "тиран вулика", en="Tyrant of the Hive" }, -- Tyrant of the Hive
[222763] = { "міксмайстер Блікс", "майстер міксології", en="Mixmaster Blix" }, -- Mixmaster Blix
[222765] = { "Жадан", "майстер темноплетіння", en="Desirous" }, -- Desirous
[222768] = { "Лізабет Ла'Моналісьє", "майстриня фазоплетіння", en="Lisabeth La'monalissier" }, -- Lisabeth La'monalissier
[222772] = { "Кримеон Лаклин", "майстер трансмутації", en="Crimeon Lablade" }, -- Crimeon Lablade
[222789] = { "Гігант", en="The Giant" }, -- The Giant
[222799] = { "кипучий елементаль", en="Simmering Elemental" }, -- Simmering Elemental
[222856] = { "дивний тотем", en="Odd Totem" }, -- Odd Totem
[222857] = { "дивний тотем", en="Odd Totem" }, -- Odd Totem
[222897] = { "розлючений пустотник", en="Enraged Voidwalker" }, -- Enraged Voidwalker
[222919] = { "вихровий буревійник", en="Whirling Tempest" }, -- Whirling Tempest
[222968] = { "Летлас", en="Lethlas" }, -- Lethlas
[222977] = { "Фантім", en="Phantim" }, -- Phantim
[222978] = { "зелений шлам", en="Green Sludge" }, -- Green Sludge
[223061] = { "заряджений тотем", en="Charged Totem" }, -- Charged Totem
[223068] = { "громоголовий гіпогриф", en="Thunderhead Hippogryph" }, -- Thunderhead Hippogryph
[223123] = { "хворий лісовий деревань", en="Diseased Forest Walker" }, -- Diseased Forest Walker
[223127] = { "мертвий хворий шаман Зловісного Тотема", en="Dead Diseased Grimtotem Shaman" }, -- Dead Diseased Grimtotem Shaman
[223128] = { "мертвий хворий дереволапий містик", en="Dead Diseased Woodpaw Mystic" }, -- Dead Diseased Woodpaw Mystic
[223130] = { "викорчований морокодрев", en="Uprooted Gloomwood" }, -- Uprooted Gloomwood
[223264] = { "несамовитий древній", en="Delirious Ancient" }, -- Delirious Ancient
[223265] = { "несамовитий древній", en="Delirious Ancient" }, -- Delirious Ancient
[223287] = { "вогняний елементаль", en="Fire Elemental" }, -- Fire Elemental
[223340] = { "загарбник Скверни", en="Fel Interloper" }, -- Fel Interloper
[223542] = { "загарбник Скверни", en="Fel Interloper" }, -- Fel Interloper
[223543] = { "загарбник Скверни", en="Fel Interloper" }, -- Fel Interloper
[223544] = { "загарбник Скверни", en="Fel Interloper" }, -- Fel Interloper
[223586] = { "Гукку", en="Hukku" }, -- Hukku
[223587] = { "Міджан", en="Mijan" }, -- Mijan
[223588] = { "Ґешер", en="Gasher" }, -- Gasher
[223590] = { "вівтар спостерігача", en="Shrine of the Watcher" }, -- Shrine of the Watcher
[223591] = { "ехо загубленої душі", en="Echo of a Lost Soul" }, -- Echo of a Lost Soul
[224242] = { "просяклий слизень", en="Saturated Ooze" }, -- Saturated Ooze
[224243] = { "глибинний маскун", en="Deep Lurker" }, -- Deep Lurker
[224244] = { "слизовий черв", en="Slime Maggot" }, -- Slime Maggot
[224245] = { "слизнюк", en="Oozeling" }, -- Oozeling
[224250] = { "воїн Атал'ай", en="Atal'ai Warrior" }, -- Atal'ai Warrior
[224253] = { "блукач кошмару", en="Nightmare Wanderer" }, -- Nightmare Wanderer
[224254] = { "драконіда кошмару", en="Nightmare Wyrmkin" }, -- Nightmare Wyrmkin
[224255] = { "лускоклят кошмару", en="Nightmare Scalebane" }, -- Nightmare Scalebane
[224256] = { "дракончик кошмару", en="Nightmare Whelp" }, -- Nightmare Whelp
[224257] = { "раб Атал'ай", en="Atal'ai Slave" }, -- Atal'ai Slave
[224258] = { "верховний жрець Атал'ай", en="Atal'ai High Priest" }, -- Atal'ai High Priest
[224259] = { "смертеступ Атал'ай", en="Atal'ai Deathwalker" }, -- Atal'ai Deathwalker
[224260] = { "трупоїд Атал'ай", en="Atal'ai Corpse Eater" }, -- Atal'ai Corpse Eater
[224262] = { "неживий троль Атал'ай", en="Unliving Atal'ai" }, -- Unliving Atal'ai
[224263] = { "знахар Атал'ай", en="Atal'ai Witch Doctor" }, -- Atal'ai Witch Doctor
[224328] = { "дослідник Залґо", "постачальник загублених речей", en="Zalgo the Explorer" }, -- Zalgo the Explorer
[224386] = { "вогнестраж-винищувач", en="Fireguard Destroyer" }, -- Fireguard Destroyer
[224743] = { "смарагдовий вартовий", en="Emerald Warden" }, -- Emerald Warden
}

if addonTable.npc then
    for k, v in pairs(npc) do addonTable.npc[k] = v end
else
    addonTable.npc = npc
end
