-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local npc = { -- [id] = { title, description (optional) }
[209889] = { "Голокіст", "продавець PvP-спорядження", en="Barebones" }, -- Barebones
}

if addonTable.npc then
    for k, v in pairs(npc) do addonTable.npc[k] = v end
else
    addonTable.npc = npc
end
