local _, addonTable = ...
addonTable.npc = { -- [id] = { title, description (optional) }
[3] = { "пожирач плоті" }, -- Flesh Eater
[6] = { "кобольд-шкідник" }, -- Kobold Vermin
[30] = { "лісовий павук" }, -- Forest Spider
[36] = { "жнивальний голем" }, -- Harvest Golem
[38] = { "розбіяка повстанців" }, -- Defias Thug
[40] = { "кобольд-шахтар" }, -- Kobold Miner
[43] = { "шахтний павук" }, -- Mine Spider
[46] = { "мурлок-здобувач" }, -- Murloc Forager
[48] = { "скелетний воїн" }, -- Skeletal Warrior
[68] = { "штормовійський вартовий" }, -- Stormwind City Guard
[69] = { "сірий вовк" }, -- Timber Wolf
[80] = { "кобольд-різнороб" }, -- Kobold Laborer
[89] = { "пекельник" }, -- Infernal
[92] = { "кам'яний елементаль" }, -- Rock Elemental
[94] = { "кишеньковий злодій повстанців" }, -- Defias Cutpurse
[95] = { "контрабандист повстанців" }, -- Defias Smuggler
[97] = { "річколапе щеня" }, -- Riverpaw Runt
[98] = { "річколапий орудар" }, -- Riverpaw Taskmaster
[113] = { "кам'янорилий кнур" }, -- Stonetusk Boar
[114] = { "жнивальний доглядач" }, -- Harvest Watcher
[115] = { "жнивальний збирач" }, -- Harvest Reaper
[116] = { "бандит повстанців" }, -- Defias Bandit
[117] = { "річколапий гнол" }, -- Riverpaw Gnoll
[118] = { "бродячий хижак" }, -- Prowler
[119] = { "довгорил" }, -- Longsnout
[121] = { "вистежувач повстанців" }, -- Defias Pathstalker
[122] = { "нальотчик повстанців" }, -- Defias Highwayman
[123] = { "річколапа дворняга" }, -- Riverpaw Mongrel
[124] = { "річколапий моцак" }, -- Riverpaw Brute
[125] = { "річколапий розпорядник" }, -- Riverpaw Overseer
[126] = { "мурлок-берегобігун" }, -- Murloc Coastrunner
[127] = { "мурлок-хвилелов" }, -- Murloc Tidehunter
[154] = { "великий плотодер" }, -- Greater Fleshripper
[157] = { "іклоштрик" }, -- Goretusk
[171] = { "мурлок-воїн" }, -- Murloc Warrior
[193] = { "синій драконід" }, -- Blue Dragonspawn
[199] = { "молодий плотодер" }, -- Young Fleshripper
[202] = { "скелетне страховище" }, -- Skeletal Horror
[203] = { "скелетний маг" }, -- Skeletal Mage
[205] = { "темний вісник Ночегибелі" }, -- Nightbane Dark Runner
[206] = { "злобне ікло Ночегибелі" }, -- Nightbane Vile Fang
[210] = { "кісткожув" }, -- Bone Chewer
[212] = { "воїн Сколотого Кулака" }, -- Splinter Fist Warrior
[213] = { "голодний зловісний вовк" }, -- Starving Dire Wolf
[215] = { "нічний вісник повстанців" }, -- Defias Night Runner
[217] = { "отруйний колопряд" }, -- Venom Web Spider
[218] = { "розкрадач могил" }, -- Grave Robber
[257] = { "кобольд-робітник" }, -- Kobold Worker
[284] = { "їздовий кінь (коричневий)" }, -- Riding Horse (Brown)
[285] = { "мурлок" }, -- Murloc
[299] = { "молодий вовк" }, -- Young Wolf
[304] = { "їздовий кінь (скверножеребець)" }, -- Riding Horse (Felsteed)
[305] = { "їздовий кінь (білий)" }, -- Riding Horse (White Stallion)
[306] = { "їздовий кінь (паломіно)" }, -- Riding Horse (Palomino)
[307] = { "їздовий кінь (рябий)" }, -- Riding Horse (Pinto)
[308] = { "їздовий кінь (чорний)" }, -- Riding Horse (Black Stallion)
[329] = { "земляний елементаль" }, -- Earth Elemental
[356] = { "їздовий вовк (чорний)" }, -- Riding Wolf (Black)
[358] = { "їздовий вовк (коричневий)" }, -- Riding Wolf (Brown)
[359] = { "їздовий вовк (зимовий)" }, -- Riding Wolf (Winter)
[385] = { "кінь" }, -- Horse
[390] = { "свинячий супровід" }, -- Porcine Entourage
[416] = { "бісеня" }, -- Imp
[417] = { "скверногонча" }, -- Felhunter
[422] = { "мурлок-живоїд" }, -- Murloc Flesheater
[423] = { "багрянокряжова дворняга" }, -- Redridge Mongrel
[424] = { "багрянокряжовий браконьєр" }, -- Redridge Poacher
[426] = { "багрянокряжовий моцак" }, -- Redridge Brute
[428] = { "зловісний кондор" }, -- Dire Condor
[429] = { "тіньошкурий темноткач" }, -- Shadowhide Darkweaver
[430] = { "багрянокряжовий містік" }, -- Redridge Mystic
[431] = { "тіньошкурий вбивця" }, -- Shadowhide Slayer
[432] = { "тіньошкурий моцак" }, -- Shadowhide Brute
[433] = { "тіньошкурий гнол" }, -- Shadowhide Gnoll
[434] = { "скажений тіньошкурий гнол" }, -- Rabid Shadowhide Gnoll
[435] = { "герой Чорнокаменю" }, -- Blackrock Champion
[436] = { "тіньомов Чорнокаменю" }, -- Blackrock Shadowcaster
[437] = { "відступник Чорнокаменю" }, -- Blackrock Renegade
[440] = { "бугай Чорнокаменю" }, -- Blackrock Grunt
[441] = { "дитинча чорного дракона" }, -- Black Dragon Whelp
[442] = { "тарантул" }, -- Tarantula
[445] = { "багрянокряжовий альфа" }, -- Redridge Alpha
[446] = { "багрянокряжове гепало" }, -- Redridge Basher
[449] = { "кастетник повстанців" }, -- Defias Knuckleduster
[450] = { "маг-відступник повстанців" }, -- Defias Renegade Mage
[452] = { "річколапий бандит" }, -- Riverpaw Bandit
[453] = { "річколапий містик" }, -- Riverpaw Mystic
[454] = { "молодий іклоштрик" }, -- Young Goretusk
[456] = { "мурлок-молодший оракул" }, -- Murloc Minor Oracle
[458] = { "мурлок-мисливець" }, -- Murloc Hunter
[467] = { "зрадник повстанців" }, -- The Defias Traitor
[468] = { "міський оповісник" }, -- Town Crier
[474] = { "чарівник-розбійник повстанців" }, -- Defias Rogue Wizard
[475] = { "кобольд-прохідник" }, -- Kobold Tunneler
[476] = { "кобольд-геомант" }, -- Kobold Geomancer
[478] = { "річколапий вістовий" }, -- Riverpaw Outrunner
[480] = { "іржавий жнивальний голем" }, -- Rusty Harvest Golem
[481] = { "харциз повстанців" }, -- Defias Footpad
[485] = { "вістовий Чорнокаменю" }, -- Blackrock Outrunner
[500] = { "річколапий розвідник" }, -- Riverpaw Scout
[501] = { "річколапий травник" }, -- Riverpaw Herbalist
[504] = { "капканник повстанців" }, -- Defias Trapper
[505] = { "великий тарантул" }, -- Greater Tarantula
[510] = { "водяний елементаль" }, -- Water Elemental
[511] = { "божевільний гуль" }, -- Insane Ghoul
[513] = { "мурлок-сіткар" }, -- Murloc Netter
[515] = { "мурлок-рейдер" }, -- Murloc Raider
[517] = { "мурлок-оракул" }, -- Murloc Oracle
[524] = { "кам'яношкурий кнур" }, -- Rockhide Boar
[525] = { "коростяний вовк" }, -- Mangy Wolf
[531] = { "скелетний негідник" }, -- Skeletal Fiend
[533] = { "тіньовий ткач Ночегибелі" }, -- Nightbane Shadow Weaver
[539] = { "карликовий отруйний колопряд" }, -- Pygmy Venom Web Spider
[541] = { "їздовий грифон" }, -- Riding Gryphon
[544] = { "мурлок-крагулець" }, -- Murloc Nightcrawler
[545] = { "мурлок-хвилезов" }, -- Murloc Tidecaller
[547] = { "великий іклоштрик" }, -- Great Goretusk
[548] = { "мурлок-молодший хвилезов" }, -- Murloc Minor Tidecaller
[550] = { "посильний повстанців" }, -- Defias Messenger
[565] = { "скажений зловісний вовк" }, -- Rabid Dire Wolf
[568] = { "тіньошкурий воїн" }, -- Shadowhide Warrior
[569] = { "зелений самітник" }, -- Green Recluse
[570] = { "мізкоїд" }, -- Brain Eater
[575] = { "вогняний елементаль" }, -- Fire Elemental
[578] = { "мурлок-розвідник" }, -- Murloc Scout
[579] = { "тіньошкурий душогуб" }, -- Shadowhide Assassin
[580] = { "багрянокряжовий чорнороб" }, -- Redridge Drudger
[583] = { "душитель повстанців" }, -- Defias Ambusher
[587] = { "воїн Кровоскальпих" }, -- Bloodscalp Warrior
[588] = { "розвідник Кровоскальпих" }, -- Bloodscalp Scout
[589] = { "грабіжник повстанців" }, -- Defias Pillager
[590] = { "здобичник повстанців" }, -- Defias Looter
[594] = { "поплічник повстанців" }, -- Defias Henchman
[595] = { "мисливець Кровоскальпих" }, -- Bloodscalp Hunter
[596] = { "вельможа з промитими мізками" }, -- Brainwashed Noble
[597] = { "берсерк Кровоскальпих" }, -- Bloodscalp Berserker
[598] = { "шахтар повстанців" }, -- Defias Miner
[604] = { "розповсюдник чуми" }, -- Plague Spreader
[615] = { "пантрувач Чорнокаменю" }, -- Blackrock Tracker
[619] = { "заклинатель повстанців" }, -- Defias Conjurer
[620] = { "курка" }, -- Chicken
[622] = { "гоблін-інженер" }, -- Goblin Engineer
[623] = { "скелетний шахтер" }, -- Skeletal Miner
[624] = { "невмерлий копач" }, -- Undead Excavator
[625] = { "невмерлий підривник" }, -- Undead Dynamiter
[628] = { "чорний спустошник" }, -- Black Ravager
[634] = { "розпорядник повстанців" }, -- Defias Overseer
[636] = { "лайдак повстанців" }, -- Defias Blackguard
[641] = { "гоблін-різьбяр по дереву" }, -- Goblin Woodcarver
[657] = { "пірат повстанців" }, -- Defias Pirate
[660] = { "знахар Кровоскальпих" }, -- Bloodscalp Witch Doctor
[667] = { "воїн Черепотрощителів" }, -- Skullsplitter Warrior
[669] = { "мисливець Черепотрощителів" }, -- Skullsplitter Hunter
[670] = { "знахар Черепотрощителів" }, -- Skullsplitter Witch Doctor
[671] = { "мисливець за головами Черепотрощителів" }, -- Skullsplitter Headhunter
[672] = { "ловець духів Черепотрощителів" }, -- Skullsplitter Spiritchaser
[674] = { "гірняк ТзНБ \"Авантюра\"" }, -- Venture Co. Strip Miner
[675] = { "десятник ТзНБ \"Авантюра\"" }, -- Venture Co. Foreman
[676] = { "землемір ТзНБ \"Авантюра\"" }, -- Venture Co. Surveyor
[677] = { "майструвальник ТзНБ \"Авантюра\"" }, -- Venture Co. Tinkerer
[678] = { "мош'оґґський молотобій" }, -- Mosh'Ogg Mauler
[679] = { "мош'оґґський шаман" }, -- Mosh'Ogg Shaman
[680] = { "мош'оґґський лорд" }, -- Mosh'Ogg Lord
[681] = { "молодий тернистодільний тигр" }, -- Young Stranglethorn Tiger
[682] = { "тернистодільний тигр" }, -- Stranglethorn Tiger
[683] = { "молода пантера" }, -- Young Panther
[684] = { "тіньопаща пантера" }, -- Shadowmaw Panther
[685] = { "тернистодільний раптор" }, -- Stranglethorn Raptor
[686] = { "хлястохвостий раптор" }, -- Lashtail Raptor
[687] = { "ловець джунглів" }, -- Jungle Stalker
[688] = { "кам'янопащий василіск" }, -- Stone Maw Basilisk
[689] = { "кришталевоколючий василіск" }, -- Crystal Spine Basilisk
[690] = { "холодноокий василіск" }, -- Cold Eye Basilisk
[691] = { "меньший водяний елементаль" }, -- Lesser Water Elemental
[694] = { "сокирожбур Кровоскальпих" }, -- Bloodscalp Axe Thrower
[696] = { "сокирожбур Черепотрощителів" }, -- Skullsplitter Axe Thrower
[697] = { "шаман Кровоскальпих" }, -- Bloodscalp Shaman
[698] = { "тигр Кровоскальпих" }, -- Bloodscalp Tiger
[699] = { "володар звірів Кровоскальпих" }, -- Bloodscalp Beastmaster
[700] = { "пантера Кровоскальпих" }, -- Bloodscalp Panther
[701] = { "містик Кровоскальпих" }, -- Bloodscalp Mystic
[702] = { "сміттяр Кровоскальпих" }, -- Bloodscalp Scavenger
[704] = { "обдертий сірий вовк" }, -- Ragged Timber Wolf
[705] = { "обдертий молодий вовк" }, -- Ragged Young Wolf
[706] = { "морозогривий молодий троль" }, -- Frostmane Troll Whelp
[707] = { "кам'янощелепий трог" }, -- Rockjaw Trogg
[708] = { "малий скельний кнур" }, -- Small Crag Boar
[709] = { "мош'оґґський войовник" }, -- Mosh'Ogg Warmonger
[710] = { "мош'оґґський висікач заклять" }, -- Mosh'Ogg Spellcrafter
[712] = { "багрянокряжовий трупоїд" }, -- Redridge Thrasher
[721] = { "кролик" }, -- Rabbit
[723] = { "мош'оґґський м'ясар" }, -- Mosh'Ogg Butcher
[724] = { "кремезний кам'янощелепий трог" }, -- Burly Rockjaw Trogg
[727] = { "залізогартський горянин" }, -- Ironforge Mountaineer
[732] = { "мурлок-маскун" }, -- Murloc Lurker
[735] = { "мурлок-річковий бігун" }, -- Murloc Streamrunner
[736] = { "пантера" }, -- Panther
[740] = { "молоде драконеня" }, -- Adolescent Whelp
[741] = { "спляче драконеня" }, -- Dreaming Whelp
[742] = { "зелена драконіда" }, -- Green Wyrmkin
[743] = { "драконіда-сновидиця" }, -- Wyrmkin Dreamwalker
[744] = { "зелений лускоклят" }, -- Green Scalebane
[745] = { "капітан-лускоклят" }, -- Scalebane Captain
[746] = { "старий драконід" }, -- Elder Dragonkin
[747] = { "трясовинний мурлок" }, -- Marsh Murloc
[750] = { "трясовинний чорнильник" }, -- Marsh Inkspewer
[751] = { "трясовинний живоїд" }, -- Marsh Flesheater
[752] = { "трясовинний оракул" }, -- Marsh Oracle
[754] = { "вартовий бунтарів" }, -- Rebel Watchman
[755] = { "загублений муловий маскун" }, -- Lost One Mudlurker
[756] = { "пантера Черепотрощителів" }, -- Skullsplitter Panther
[757] = { "загублений рибалка" }, -- Lost One Fisherman
[758] = { "тигр Черепотрощителів" }, -- Skullsplitter Tiger
[759] = { "загублений мисливець" }, -- Lost One Hunter
[760] = { "загублений бруднуля" }, -- Lost One Muckdweller
[761] = { "загублений провидець" }, -- Lost One Seer
[762] = { "загублений шукач розламів" }, -- Lost One Riftseeker
[763] = { "загублений ватаг" }, -- Lost One Chieftain
[764] = { "болотний блукач" }, -- Swampwalker
[765] = { "старий болотний блукач" }, -- Swampwalker Elder
[766] = { "кривулясте страховище" }, -- Tangled Horror
[767] = { "болотний ягуар" }, -- Swamp Jaguar
[768] = { "тіньова пантера" }, -- Shadow Panther
[769] = { "смертоносний тарантул" }, -- Deathstrike Tarantula
[772] = { "тернистодільна тигриця" }, -- Stranglethorn Tigress
[775] = { "агент Курцена" }, -- Kurzen's Agent
[780] = { "містик Черепотрощителів" }, -- Skullsplitter Mystic
[781] = { "мисливець за головами Черепотрощителів" }, -- Skullsplitter Headhunter
[782] = { "розвідник Черепотрощителів" }, -- Skullsplitter Scout
[783] = { "берсерк Черепотрощителів" }, -- Skullsplitter Berserker
[784] = { "володар звірів Черепотрощителів" }, -- Skullsplitter Beastmaster
[785] = { "скелетний чатовий" }, -- Skeletal Warder
[787] = { "скелетний цілитель" }, -- Skeletal Healer
[819] = { "слуга Ілґалара" }, -- Servant of Ilgalar
[822] = { "молодий лісовий ведмідь" }, -- Young Forest Bear
[824] = { "землекоп повстанців" }, -- Defias Digger
[830] = { "піщаний повзун" }, -- Sand Crawler
[831] = { "морський повзун" }, -- Sea Crawler
[832] = { "пиловий дідько" }, -- Dust Devil
[833] = { "койот-лідер зграї" }, -- Coyote Packleader
[834] = { "койот" }, -- Coyote
[842] = { "лісоруб" }, -- Lumberjack
[846] = { "гуль" }, -- Ghoul
[853] = { "морознодільний горянин" }, -- Coldridge Mountaineer
[854] = { "молодий ловець джунглів" }, -- Young Jungle Stalker
[855] = { "молодий тернистодільний раптор" }, -- Young Stranglethorn Raptor
[856] = { "молодий хлястохвостий раптор" }, -- Young Lashtail Raptor
[857] = { "ткач скорботи" }, -- Sorrow Spinner
[861] = { "камінардський розвідник" }, -- Stonard Scout
[862] = { "камінардський дослідник" }, -- Stonard Explorer
[863] = { "камінардський мисливець" }, -- Stonard Hunter
[864] = { "камінардський орк" }, -- Stonard Orc
[865] = { "камінардський прокладач шляху" }, -- Stonard Wayfinder
[866] = { "камінардський бугай" }, -- Stonard Grunt
[867] = { "камінардський картограф" }, -- Stonard Cartographer
[868] = { "камінардський шаман" }, -- Stonard Shaman
[871] = { "солонолуский воїн" }, -- Saltscale Warrior
[873] = { "солонолуский оракул" }, -- Saltscale Oracle
[875] = { "солонолуский лорд хвиль" }, -- Saltscale Tide Lord
[877] = { "солонолуский здобувач" }, -- Saltscale Forager
[879] = { "солонолуский мисливець" }, -- Saltscale Hunter
[883] = { "олень" }, -- Deer
[889] = { "орг Сколотого Кулака" }, -- Splinter Fist Ogre
[890] = { "оленя" }, -- Fawn
[891] = { "вогнеткач Сколотого Кулака" }, -- Splinter Fist Fire Weaver
[892] = { "орудар Сколотого Кулака" }, -- Splinter Fist Taskmaster
[898] = { "ворген Ночегибелі" }, -- Nightbane Worgen
[905] = { "гострозуба навіженка" }, -- Sharptooth Frenzy
[909] = { "нічне лезо повстанців" }, -- Defias Night Blade
[910] = { "чародій повстанців" }, -- Defias Enchanter
[920] = { "плюгавець Ночегибелі" }, -- Nightbane Tainted One
[921] = { "лісоруб ТзНБ \"Авантюра\"" }, -- Venture Co. Lumberjack
[922] = { "муловий повзун" }, -- Silt Crawler
[923] = { "молодий чорний спустошник" }, -- Young Black Ravager
[930] = { "дитинча чорної вдови" }, -- Black Widow Hatchling
[937] = { "лісовий боєць Курцена" }, -- Kurzen Jungle Fighter
[938] = { "командос Курцена" }, -- Kurzen Commando
[939] = { "елітний боєць Курцена" }, -- Kurzen Elite
[940] = { "медик Курцена" }, -- Kurzen Medicine Man
[941] = { "головодав Курцена" }, -- Kurzen Headshrinker
[942] = { "знахар Курцена" }, -- Kurzen Witch Doctor
[943] = { "чередник Курцена" }, -- Kurzen Wrangler
[946] = { "морозогривий послушник" }, -- Frostmane Novice
[948] = { "гниляк" }, -- Rotted One
[949] = { "мертвоїд-самітник" }, -- Carrion Recluse
[1172] = { "тунельний щур-шкідник" }, -- Tunnel Rat Vermin
[1173] = { "тунельний щур-розвідник" }, -- Tunnel Rat Scout
[1174] = { "тунельний щур-геомант" }, -- Tunnel Rat Geomancer
[1175] = { "тунельний щур-землекоп" }, -- Tunnel Rat Digger
[1176] = { "тунельний щур-здобувач" }, -- Tunnel Rat Forager
[1177] = { "тунельний щур-землемір" }, -- Tunnel Rat Surveyor
[1504] = { "молодий нічний колопряд" }, -- Young Night Web Spider
[1505] = { "нічний колопряд" }, -- Night Web Spider
[1512] = { "сутінковий кажан" }, -- Duskbat
[1522] = { "темноокий скелет-заклинач" }, -- Darkeye Bonecaster
[1523] = { "солдат з пробитим черепом" }, -- Cracked Skull Soldier
[1529] = { "криваве страховище" }, -- Bleeding Horror
[1530] = { "гниючий предок" }, -- Rotting Ancestor
[1532] = { "блукаючий дух" }, -- Wandering Spirit
[1534] = { "тужливий предок" }, -- Wailing Ancestor
[1555] = { "злий нічний колопряд" }, -- Vicious Night Web Spider
[1675] = { "гнилошкура дворняга" }, -- Rot Hide Mongrel
[1756] = { "королівський гвардієць Штормовія" }, -- Stormwind Royal Guard
[1765] = { "ворг" }, -- Worg
[1766] = { "плямистий ворг" }, -- Mottled Worg
[1767] = { "подрібнювач Злобного Плавника" }, -- Vile Fin Shredder
[1768] = { "хвилелов Злобного Плавника" }, -- Vile Fin Tidehunter
[1769] = { "білоскальп Місяцесказу" }, -- Moonrage Whitescalp
[1779] = { "ненажера Місяцесказу" }, -- Moonrage Glutton
[1782] = { "темний дух Місяцесказу" }, -- Moonrage Darksoul
[1860] = { "пустотник" }, -- Voidwalker
[1863] = { "сукуб" }, -- Succubus
[1865] = { "рейдер Воронокігтя" }, -- Ravenclaw Raider
[1866] = { "невільник Воронокігтя" }, -- Ravenclaw Slave
[1867] = { "даларанський учень" }, -- Dalaran Apprentice
[1868] = { "слуга Воронокігтя" }, -- Ravenclaw Servant
[1869] = { "герой Воронокігтя" }, -- Ravenclaw Champion
[1870] = { "десниця Воронокігтя" }, -- Hand of Ravenclaw
[1871] = { "вартовий Елізи" }, -- Eliza's Guard
[1883] = { "робітник Багряного Походу" }, -- Scarlet Worker
[1884] = { "лісоруб Багряного Походу" }, -- Scarlet Lumberjack
[1885] = { "коваль Багряного Походу" }, -- Scarlet Smith
[1888] = { "даларанський наглядач" }, -- Dalaran Watcher
[1889] = { "даларанський чарівник" }, -- Dalaran Wizard
[1890] = { "брязкокістковий скелет" }, -- Rattlecage Skeleton
[1891] = { "наглядач Поховальних Вогнищ" }, -- Pyrewood Watcher
[1892] = { "наглядач Місяцесказу" }, -- Moonrage Watcher
[1893] = { "караульний Місяцесказу" }, -- Moonrage Sentry
[1894] = { "караульний Поховальних Вогнищ" }, -- Pyrewood Sentry
[1895] = { "старійшина Поховальних Вогнищ" }, -- Pyrewood Elder
[1896] = { "старійшина Місяцесказу" }, -- Moonrage Elder
[1907] = { "нага-дослідник" }, -- Naga Explorer
[1908] = { "оракул Злобного Плавника" }, -- Vile Fin Oracle
[1909] = { "озерний ловчий Злобного Плавника" }, -- Vile Fin Lakestalker
[1912] = { "даларанський захисник" }, -- Dalaran Protector
[1913] = { "даларанський чатовий" }, -- Dalaran Warder
[1914] = { "даларанський маг" }, -- Dalaran Mage
[1915] = { "даларанський заклинатель" }, -- Dalaran Conjuror
[1920] = { "даларанський писар заклинань" }, -- Dalaran Spellscribe
[1922] = { "сірий лісовий вовк" }, -- Gray Forest Wolf
[1923] = { "кровожерливий ворг" }, -- Bloodsnout Worg
[1924] = { "кроворев Місяцесказу" }, -- Moonrage Bloodhowler
[1939] = { "гнилошкурий моцак" }, -- Rot Hide Brute
[1940] = { "гнилошкурий чумоткач" }, -- Rot Hide Plague Weaver
[1941] = { "гнилошкурий розкрадач могил" }, -- Rot Hide Graverobber
[1942] = { "гнилошкурий дикун" }, -- Rot Hide Savage
[1943] = { "розлючений гнилошкур" }, -- Raging Rot Hide
[1944] = { "гнилошкурий забіяка" }, -- Rot Hide Bruiser
[1953] = { "oзерний тайноходець" }, -- Lake Skulker
[1954] = { "старий oзерний тайноходець" }, -- Elder Lake Skulker
[1955] = { "озерний підкрадач" }, -- Lake Creeper
[1956] = { "старий озерний підкрадач" }, -- Elder Lake Creeper
[1957] = { "береговий розвідник Злобного Плавника" }, -- Vile Fin Shorecreeper
[1958] = { "хвилезов Злобного Плавника" }, -- Vile Fin Tidecaller
[1973] = { "вартовий Воронокігтя" }, -- Ravenclaw Guardian
[1974] = { "чорнороб Воронокігтя" }, -- Ravenclaw Drudger
[1975] = { "лісоруб Східнодолу" }, -- Eastvale Lumberjack
[1976] = { "штормовійський патрульний" }, -- Stormwind City Patroller
[1986] = { "павутиннолісий павук" }, -- Webwood Spider
[1988] = { "грел" }, -- Grell
[1989] = { "грелід" }, -- Grellkin
[1995] = { "сова-сипуха" }, -- Strigid Owl
[1996] = { "сова-верескун" }, -- Strigid Screecher
[1997] = { "сова-мисливець" }, -- Strigid Hunter
[1998] = { "павутиннолісий маскун" }, -- Webwood Lurker
[1999] = { "павутиннолісий отрутозуб" }, -- Webwood Venomfang
[2000] = { "павутиннолісий шовков'яз" }, -- Webwood Silkspinner
[2001] = { "велетеньский павутиннолісий павук" }, -- Giant Webwood Spider
[2005] = { "злий грел" }, -- Vicious Grell
[2006] = { "урса Кривої Сосни" }, -- Gnarlpine Ursa
[2007] = { "садівник Кривої Сосни" }, -- Gnarlpine Gardener
[2008] = { "воїн Кривої Сосни" }, -- Gnarlpine Warrior
[2009] = { "шаман Кривої Сосни" }, -- Gnarlpine Shaman
[2010] = { "захисник Кривої Сосни" }, -- Gnarlpine Defender
[2011] = { "авгур Кривої Сосни" }, -- Gnarlpine Augur
[2012] = { "слідопит Кривої Сосни" }, -- Gnarlpine Pathfinder
[2013] = { "месник Кривої Сосни" }, -- Gnarlpine Avenger
[2014] = { "тотеміст Кривої Сосни" }, -- Gnarlpine Totemic
[2015] = { "кривавопера гарпія" }, -- Bloodfeather Harpy
[2017] = { "кривавопера розбійниця" }, -- Bloodfeather Rogue
[2018] = { "кривавопера чаклунка" }, -- Bloodfeather Sorceress
[2019] = { "кривавопера фурія" }, -- Bloodfeather Fury
[2020] = { "кривавопера вітровідьма" }, -- Bloodfeather Wind Witch
[2021] = { "кривавопера матріарх" }, -- Bloodfeather Matriarch
[2022] = { "деревник" }, -- Timberling
[2025] = { "деревник-корервач" }, -- Timberling Bark Ripper
[2027] = { "деревник-топотун" }, -- Timberling Trampler
[2029] = { "деревник-болотяник" }, -- Timberling Mire Beast
[2030] = { "старий деревник" }, -- Elder Timberling
[2031] = { "молодий ночезуб" }, -- Young Nightsaber
[2032] = { "коростяний ночезуб" }, -- Mangy Nightsaber
[2033] = { "старий ночезуб" }, -- Elder Nightsaber
[2034] = { "здичавілий ночезуб" }, -- Feral Nightsaber
[2041] = { "древній захисник" }, -- Ancient Protector
[2042] = { "ночезуб" }, -- Nightsaber
[2043] = { "ночезуб-ловець" }, -- Nightsaber Stalker
[2044] = { "забутий дух" }, -- Forlorn Spirit
[2053] = { "змучений біженець" }, -- Haggard Refugee
[2054] = { "кволий біженець" }, -- Sickly Refugee
[2056] = { "мара Воронокігтя" }, -- Ravenclaw Apparition
[2069] = { "місяцескрад" }, -- Moonstalker
[2070] = { "молодий місяцескрад" }, -- Moonstalker Runt
[2071] = { "місяцескрад-матріарх" }, -- Moonstalker Matriarch
[2089] = { "велетенський кроколіск Заболоття" }, -- Giant Wetlands Crocolisk
[2098] = { "баран" }, -- Ram
[2099] = { "член команди \"Дівоча цнота\"" }, -- Maiden's Virtue Crewman
[2102] = { "бугай Драконопащих" }, -- Dragonmaw Grunt
[2103] = { "розвідник Драконопащих" }, -- Dragonmaw Scout
[2110] = { "чорний пацюк" }, -- Black Rat
[2149] = { "рейдер Темного Заліза" }, -- Dark Iron Raider
[2152] = { "душитель Кривої Сосни" }, -- Gnarlpine Ambusher
[2156] = { "потрісканий голем" }, -- Cracked Golem
[2157] = { "кам'яна почвара" }, -- Stone Behemoth
[2158] = { "гравієкремневий розвідник" }, -- Gravelflint Scout
[2159] = { "гравієкремневий кісткохруст" }, -- Gravelflint Bonesnapper
[2160] = { "гравієкремневий геомант" }, -- Gravelflint Geomancer
[2163] = { "татарний ведмідь" }, -- Thistle Bear
[2164] = { "скажений татарний ведмідь" }, -- Rabid Thistle Bear
[2165] = { "посивілий татарний ведмідь" }, -- Grizzled Thistle Bear
[2167] = { "чорнолісний слідопит" }, -- Blackwood Pathfinder
[2168] = { "чорнолісний воїн" }, -- Blackwood Warrior
[2169] = { "чорнолісний тотеміст" }, -- Blackwood Totemic
[2170] = { "чорнолісний урса" }, -- Blackwood Ursa
[2171] = { "чорнолісний шаман" }, -- Blackwood Shaman
[2173] = { "рифова навіженка" }, -- Reef Frenzy
[2174] = { "прибережна навіженка" }, -- Coastal Frenzy
[2176] = { "проклята високородна" }, -- Cursed Highborne
[2177] = { "судорожний високородний" }, -- Writhing Highborne
[2178] = { "стогнуча високородна" }, -- Wailing Highborne
[2179] = { "штормолуский хвильогін" }, -- Stormscale Wave Rider
[2180] = { "штормолуска сирена" }, -- Stormscale Siren
[2181] = { "штормолуский мірмідон" }, -- Stormscale Myrmidon
[2182] = { "штормолуска чаклунка" }, -- Stormscale Sorceress
[2183] = { "штормолуский воїн" }, -- Stormscale Warrior
[2185] = { "молотник Темнобережжя" }, -- Darkshore Thresher
[2187] = { "старий молотник Темнобережжя" }, -- Elder Darkshore Thresher
[2188] = { "глибоководний молотодон" }, -- Deep Sea Threshadon
[2189] = { "злобний дух" }, -- Vile Sprite
[2190] = { "дикий грел" }, -- Wild Grell
[2201] = { "сіромлистий рейдер" }, -- Greymist Raider
[2202] = { "сіромлистий берегобігун" }, -- Greymist Coastrunner
[2203] = { "сіромлистий провидець" }, -- Greymist Seer
[2204] = { "сіромлистий сіткар" }, -- Greymist Netter
[2205] = { "сіромлистий воїн" }, -- Greymist Warrior
[2206] = { "сіромлистий мисливець" }, -- Greymist Hunter
[2207] = { "сіромлистий оракул" }, -- Greymist Oracle
[2208] = { "сіромлистий хвилелов" }, -- Greymist Tidehunter
[2211] = { "полонений горянин" }, -- Captured Mountaineer
[2212] = { "дет'ріллський сатир" }, -- Deth'ryll Satyr
[2231] = { "карликовий хвилевий повзун" }, -- Pygmy Tide Crawler
[2232] = { "хвилевий повзун" }, -- Tide Crawler
[2233] = { "потертий хвилевий повзун" }, -- Encrusted Tide Crawler
[2234] = { "молодий рифовий повзун" }, -- Young Reef Crawler
[2235] = { "рифовий повзун" }, -- Reef Crawler
[2236] = { "розлючений рифовий повзун" }, -- Raging Reef Crawler
[2237] = { "дорослий місяцескрад" }, -- Moonstalker Sire
[2240] = { "харциз Синдикату" }, -- Syndicate Footpad
[2241] = { "злодій Синдикату" }, -- Syndicate Thief
[2242] = { "шпигун Синдикату" }, -- Syndicate Spy
[2243] = { "караульний Синдикату" }, -- Syndicate Sentry
[2244] = { "тіньовий маг Синдикату" }, -- Syndicate Shadow Mage
[2245] = { "диверсант Синдикату" }, -- Syndicate Saboteur
[2246] = { "душогуб Синдикату" }, -- Syndicate Assassin
[2247] = { "громило Синдикату" }, -- Syndicate Enforcer
[2248] = { "печерний єті" }, -- Cave Yeti
[2249] = { "лютий єті" }, -- Ferocious Yeti
[2250] = { "гірський єті" }, -- Mountain Yeti
[2251] = { "велетенський єті" }, -- Giant Yeti
[2252] = { "скелеламський огр" }, -- Crushridge Ogre
[2253] = { "скелеламський моцак" }, -- Crushridge Brute
[2254] = { "скелеламський молотобій" }, -- Crushridge Mauler
[2255] = { "скелеламський маг" }, -- Crushridge Mage
[2256] = { "скелеламський громило" }, -- Crushridge Enforcer
[2258] = { "кам'яна лють" }, -- Stone Fury
[2260] = { "розбійник Синдикату" }, -- Syndicate Rogue
[2261] = { "вартовий Синдикату" }, -- Syndicate Watchman
[2264] = { "гіллзбрадський кравець" }, -- Hillsbrad Tailor
[2265] = { "гіллзбрадський учень коваля" }, -- Hillsbrad Apprentice Blacksmith
[2266] = { "гіллзбрадський фермер" }, -- Hillsbrad Farmer
[2267] = { "гіллзбрадський селянин" }, -- Hillsbrad Peasant
[2268] = { "гіллзбрадський піхотинець" }, -- Hillsbrad Footman
[2269] = { "гіллзбрадський шахтар" }, -- Hillsbrad Miner
[2270] = { "гіллзбрадський караульний" }, -- Hillsbrad Sentry
[2271] = { "вартовий даларанського щита" }, -- Dalaran Shield Guard
[2272] = { "даларанський ворожбит" }, -- Dalaran Theurgist
[2283] = { "регент Воронокігтя" }, -- Ravenclaw Regent
[2284] = { "полонений фермер" }, -- Captured Farmer
[2287] = { "скелеламський войовник" }, -- Crushridge Warmonger
[2318] = { "арґуський тіньовий маг" }, -- Argus Shadow Mage
[2319] = { "чарівник Синдикату" }, -- Syndicate Wizard
[2321] = { "молодий лісобіг" }, -- Foreststrider Fledgling
[2322] = { "лісобіг" }, -- Foreststrider
[2323] = { "велетенський лісобіг" }, -- Giant Foreststrider
[2324] = { "чорнолісний вітробай" }, -- Blackwood Windtalker
[2336] = { "фанатик Темного Берега" }, -- Dark Strand Fanatic
[2337] = { "пустозов Темного Берега" }, -- Dark Strand Voidcaller
[2338] = { "сутінковий послідовник" }, -- Twilight Disciple
[2339] = { "сутінковий розбіяка" }, -- Twilight Thug
[2344] = { "дун-ґароцький горянин" }, -- Dun Garok Mountaineer
[2345] = { "дун-ґароцький стрілець" }, -- Dun Garok Rifleman
[2346] = { "дун-ґароцький жрець" }, -- Dun Garok Priest
[2347] = { "дикий грифон" }, -- Wild Gryphon
[2348] = { "старий моховий підкрадач" }, -- Elder Moss Creeper
[2349] = { "велетенський моховий підкрадач" }, -- Giant Moss Creeper
[2350] = { "лісовий моховий підкрадач" }, -- Forest Moss Creeper
[2351] = { "сірий ведмідь" }, -- Gray Bear
[2354] = { "злий сірий ведмідь" }, -- Vicious Gray Bear
[2356] = { "старий сірий ведмідь" }, -- Elder Gray Bear
[2358] = { "даларанський закликач" }, -- Dalaran Summoner
[2359] = { "елементаль-невільник" }, -- Elemental Slave
[2360] = { "гіллзбрадський робітник" }, -- Hillsbrad Farmhand
[2368] = { "береговий ловчий Клинкоспинів" }, -- Daggerspine Shorestalker
[2369] = { "береговий мисливець Клинкоспинів" }, -- Daggerspine Shorehunter
[2370] = { "крикунка Клинкоспинів" }, -- Daggerspine Screamer
[2371] = { "сирена Клинкоспинів" }, -- Daggerspine Siren
[2372] = { "брудномордий гнол" }, -- Mudsnout Gnoll
[2373] = { "брудномордий шаман" }, -- Mudsnout Shaman
[2374] = { "бруднуля Розірваного Плавника" }, -- Torn Fin Muckdweller
[2375] = { "берегобігун Розірваного Плавника" }, -- Torn Fin Coastrunner
[2376] = { "оракул Розірваного Плавника" }, -- Torn Fin Oracle
[2377] = { "хвилелов Розірваного Плавника" }, -- Torn Fin Tidehunter
[2384] = { "голодний гірський лев" }, -- Starving Mountain Lion
[2385] = { "здичавілий гірський лев" }, -- Feral Mountain Lion
[2386] = { "південнобережний вартовий" }, -- Southshore Guard
[2387] = { "гіллзбрадський радник" }, -- Hillsbrad Councilman
[2442] = { "корова" }, -- Cow
[2554] = { "в'ялошкірий сокирожбур" }, -- Witherbark Axe Thrower
[2555] = { "в'ялошкірий знахар" }, -- Witherbark Witch Doctor
[2556] = { "в'ялошкірий мисливець за головами" }, -- Witherbark Headhunter
[2559] = { "плоскогірний бігун" }, -- Highland Strider
[2560] = { "плоскогірний трупоїд" }, -- Highland Thrasher
[2561] = { "плоскогірний м'ясоїд" }, -- Highland Fleshstalker
[2566] = { "брилорукий моцак" }, -- Boulderfist Brute
[2567] = { "брилорукий чаклун" }, -- Boulderfist Magus
[2569] = { "брилорукий молотобій" }, -- Boulderfist Mauler
[2570] = { "брилорукий шаман" }, -- Boulderfist Shaman
[2571] = { "брилорукий лорд" }, -- Boulderfist Lord
[2572] = { "суховусий кобольд" }, -- Drywhisker Kobold
[2573] = { "суховусий землемір" }, -- Drywhisker Surveyor
[2574] = { "суховусий землекоп" }, -- Drywhisker Digger
[2575] = { "постачальник Темного Заліза" }, -- Dark Iron Supplier
[2577] = { "тіньомов Темного Заліза" }, -- Dark Iron Shadowcaster
[2578] = { "молодий плоскогірний канюк" }, -- Young Mesa Buzzard
[2579] = { "плоскогірний канюк" }, -- Mesa Buzzard
[2580] = { "старий плоскогірний канюк" }, -- Elder Mesa Buzzard
[2581] = { "ополченець хутору Дабірі" }, -- Dabyrie Militia
[2582] = { "різнороб хутору Дабірі" }, -- Dabyrie Laborer
[2583] = { "штромґардський мисливець на тролів" }, -- Stromgarde Troll Hunter
[2584] = { "штромґардський захисник" }, -- Stromgarde Defender
[2585] = { "штромґардський покровитель" }, -- Stromgarde Vindicator
[2586] = { "нальотчик Синдикату" }, -- Syndicate Highwayman
[2587] = { "вистежувач Синдикату" }, -- Syndicate Pathstalker
[2588] = { "скрадач Синдикату" }, -- Syndicate Prowler
[2589] = { "найманець Синдикату" }, -- Syndicate Mercenary
[2590] = { "заклинатель Синдикату" }, -- Syndicate Conjuror
[2591] = { "чаклун Синдикату" }, -- Syndicate Magus
[2595] = { "рейдер Клинкоспинів" }, -- Daggerspine Raider
[2596] = { "чарівниця Клинкоспинів" }, -- Daggerspine Sorceress
[2618] = { "наймит Молотобою" }, -- Hammerfall Peon
[2619] = { "бугай Молотобою" }, -- Hammerfall Grunt
[2620] = { "степове цуценя" }, -- Prairie Dog
[2621] = { "вартовий Молотобою" }, -- Hammerfall Guardian
[2623] = { "дух давнини" }, -- Spirit of Old
[2659] = { "гостродзьобий володар неба" }, -- Razorbeak Skylord
[2775] = { "мародер Клинкоспинів" }, -- Daggerspine Marauder
[2776] = { "мстивий сплеск" }, -- Vengeful Surge
[2955] = { "рівнинобіг" }, -- Plainstrider
[2956] = { "дорослий рівнинобіг" }, -- Adult Plainstrider
[2957] = { "старий рівнинобіг" }, -- Elder Plainstrider
[2958] = { "степовий вовк" }, -- Prairie Wolf
[2959] = { "степовий ловець" }, -- Prairie Stalker
[2960] = { "степовий вовк-альфа" }, -- Prairie Wolf Alpha
[2961] = { "гірська пума" }, -- Mountain Cougar
[2962] = { "вітролюта гарпія" }, -- Windfury Harpy
[2963] = { "вітролюта вітровідьма" }, -- Windfury Wind Witch
[2964] = { "вітролюта чарівниця" }, -- Windfury Sorceress
[2965] = { "вітролюта матріарх" }, -- Windfury Matriarch
[2966] = { "бойовий кнур" }, -- Battleboar
[2967] = { "кентавр племені Ґалак" }, -- Galak Centaur
[2968] = { "вістовий племені Ґалак" }, -- Galak Outrunner
[2969] = { "жилавий хапун" }, -- Wiry Swoop
[2970] = { "хапун" }, -- Swoop
[2971] = { "пазуристий хапун" }, -- Taloned Swoop
[2972] = { "теля кодо" }, -- Kodo Calf
[2973] = { "бик кодо" }, -- Kodo Bull
[2974] = { "матріарх кодо" }, -- Kodo Matriarch
[2975] = { "найманець ТзНБ \"Авантюра\"" }, -- Venture Co. Hireling
[2976] = { "різнороб ТзНБ \"Авантюра\"" }, -- Venture Co. Laborer
[2977] = { "орудар ТзНБ \"Авантюра\"" }, -- Venture Co. Taskmaster
[2978] = { "робітник ТзНБ \"Авантюра\"" }, -- Venture Co. Worker
[2979] = { "керівник ТзНБ \"Авантюра\"" }, -- Venture Co. Supervisor
[3098] = { "крапчатий кнур" }, -- Mottled Boar
[3099] = { "лютий крапчатий кнур" }, -- Dire Mottled Boar
[3100] = { "старий крапчатий кнур" }, -- Elder Mottled Boar
[3101] = { "підлий фамільяр" }, -- Vile Familiar
[3102] = { "сквернолов" }, -- Felstalker
[3103] = { "макрура-клацало" }, -- Makrura Clacker
[3104] = { "скарлупошкіра макрура" }, -- Makrura Shellhide
[3105] = { "макрура-клешньоклацало" }, -- Makrura Snapclaw
[3106] = { "карликовий береговий повзун" }, -- Pygmy Surf Crawler
[3107] = { "береговий повзун" }, -- Surf Crawler
[3108] = { "потрісканий береговий повзун" }, -- Encrusted Surf Crawler
[3110] = { "жахопащий кроколіск" }, -- Dreadmaw Crocolisk
[3111] = { "бритвогривий свинобраз" }, -- Razormane Quilboar
[3112] = { "бритвогривий розвідник" }, -- Razormane Scout
[3113] = { "бритвогривий пилобіг" }, -- Razormane Dustrunner
[3114] = { "бритвогривий боєстраж" }, -- Razormane Battleguard
[3115] = { "пиловітрова гарпія" }, -- Dustwind Harpy
[3116] = { "пиловітрова грабіжниця" }, -- Dustwind Pillager
[3117] = { "пиловітрова дикунка" }, -- Dustwind Savage
[3118] = { "пиловітрова штормовідьма" }, -- Dustwind Storm Witch
[3119] = { "колкарський чорнороб" }, -- Kolkar Drudge
[3120] = { "колкарський вістовий" }, -- Kolkar Outrunner
[3121] = { "дуротарський тигр" }, -- Durotar Tiger
[3122] = { "кривавопазуровий хвостохляст" }, -- Bloodtalon Taillasher
[3123] = { "кривавопазуровий косопащ" }, -- Bloodtalon Scythemaw
[3124] = { "скорпід-робітник" }, -- Scorpid Worker
[3125] = { "скорпід-цокало" }, -- Clattering Scorpid
[3126] = { "броньований скорпід" }, -- Armored Scorpid
[3127] = { "отрутохвостий скорпід" }, -- Venomtail Scorpid
[3128] = { "кул-тіраський моряк" }, -- Kul Tiras Sailor
[3129] = { "кул-тіраський морський піхотинець" }, -- Kul Tiras Marine
[3130] = { "громоящір" }, -- Thunder Lizard
[3131] = { "блискавкошкур" }, -- Lightning Hide
[3141] = { "макрура-старійшина" }, -- Makrura Elder
[3195] = { "вбивця Палаючого Леза" }, -- Burning Blade Thug
[3196] = { "неофіт Палаючого Леза" }, -- Burning Blade Neophyte
[3197] = { "фанатик Палаючого Леза" }, -- Burning Blade Fanatic
[3198] = { "учень Палаючого Леза" }, -- Burning Blade Apprentice
[3199] = { "культист Палаючого Леза" }, -- Burning Blade Cultist
[3206] = { "троль вуду" }, -- Voodoo Troll
[3207] = { "зачарований троль" }, -- Hexed Troll
[3225] = { "споганений крапчатий кнур" }, -- Corrupted Mottled Boar
[3226] = { "споганений скорпід" }, -- Corrupted Scorpid
[3227] = { "споганений кривавопазуровий косопащ" }, -- Corrupted Bloodtalon Scythemaw
[3228] = { "споганений береговий повзун" }, -- Corrupted Surf Crawler
[3231] = { "споганений жахопащий кроколіск" }, -- Corrupted Dreadmaw Crocolisk
[3232] = { "щетиношкурий встрягач" }, -- Bristleback Interloper
[3238] = { "бурешкур" }, -- Stormhide
[3239] = { "громоглов" }, -- Thunderhead
[3240] = { "буреморд" }, -- Stormsnout
[3241] = { "патріарх савани" }, -- Savannah Patriarch
[3242] = { "жевра-скакун" }, -- Zhevra Runner
[3243] = { "високогрив савани" }, -- Savannah Highmane
[3244] = { "великий рівнинобіг" }, -- Greater Plainstrider
[3245] = { "злісний рівнинобіг" }, -- Ornery Plainstrider
[3246] = { "прудкий рівнинобіг" }, -- Fleeting Plainstrider
[3247] = { "пташа громояструба" }, -- Thunderhawk Hatchling
[3248] = { "степова жирафа" }, -- Barrens Giraffe
[3249] = { "великий громояструб" }, -- Greater Thunderhawk
[3250] = { "сілітід-підкрадач" }, -- Silithid Creeper
[3251] = { "личинка сілітіда" }, -- Silithid Grub
[3252] = { "сілітід-ройовик" }, -- Silithid Swarmer
[3253] = { "сілітід-збирач" }, -- Silithid Harvester
[3254] = { "сонцелуский хлястохвіст" }, -- Sunscale Lashtail
[3255] = { "сонцелуский верескун" }, -- Sunscale Screecher
[3256] = { "сонцелуский серпопазур" }, -- Sunscale Scytheclaw
[3258] = { "щетиношкурий мисливець" }, -- Bristleback Hunter
[3259] = { "щетиношкурий захисник" }, -- Bristleback Defender
[3260] = { "щетиношкурий водошукач" }, -- Bristleback Water Seeker
[3261] = { "щетиношкурий терноткач" }, -- Bristleback Thornweaver
[3262] = { "щетиношкурий містик" }, -- Bristleback Mystic
[3263] = { "щетиношкурий геомант" }, -- Bristleback Geomancer
[3265] = { "бритвогривий мисливець" }, -- Razormane Hunter
[3266] = { "бритвогривий захисник" }, -- Razormane Defender
[3267] = { "бритвогривий водошукач" }, -- Razormane Water Seeker
[3268] = { "бритвогривий терноткач" }, -- Razormane Thornweaver
[3269] = { "бритвогривий геомант" }, -- Razormane Geomancer
[3271] = { "бритвогривий містик" }, -- Razormane Mystic
[3272] = { "колкарський чередник" }, -- Kolkar Wrangler
[3273] = { "колкарська буревійка" }, -- Kolkar Stormer
[3274] = { "колкарський чабан" }, -- Kolkar Pack Runner
[3275] = { "колкарський мародер" }, -- Kolkar Marauder
[3276] = { "чарокрила гарпія" }, -- Witchwing Harpy
[3277] = { "чарокрила оперена розбійниця" }, -- Witchwing Roguefeather
[3278] = { "чарокрила вбивця" }, -- Witchwing Slayer
[3279] = { "чарокрила душителька" }, -- Witchwing Ambusher
[3280] = { "чарокрила вітрозовка" }, -- Witchwing Windcaller
[3282] = { "найманець ТзНБ \"Авантюра\"" }, -- Venture Co. Mercenary
[3283] = { "громило ТзНБ \"Авантюра\"" }, -- Venture Co. Enforcer
[3284] = { "чорнороб ТзНБ \"Авантюра\"" }, -- Venture Co. Drudger
[3285] = { "наймит ТзНБ \"Авантюра\"" }, -- Venture Co. Peon
[3286] = { "розпорядник ТзНБ \"Авантюра\"" }, -- Venture Co. Overseer
[3295] = { "шламова потвора" }, -- Sludge Beast
[3296] = { "оргрімарський бугай" }, -- Orgrimmar Grunt
[3297] = { "сен'джинський вартовий" }, -- Sen'jin Watcher
[3300] = { "гадюка" }, -- Adder
[3424] = { "громояструб-захмарник" }, -- Thunderhawk Cloudscraper
[3425] = { "бродячий хижак савани" }, -- Savannah Prowler
[3426] = { "жевра-рисак" }, -- Zhevra Charger
[3456] = { "бритвогривий слідопит" }, -- Razormane Pathfinder
[3457] = { "бритвогривий ловець" }, -- Razormane Stalker
[3458] = { "бритвогривий провидець" }, -- Razormane Seer
[3459] = { "бритвогривий очман" }, -- Razormane Warfrenzy
[3461] = { "оазисний тріскощелеп" }, -- Oasis Snapjaw
[3463] = { "блукаюча степова жирафа" }, -- Wandering Barrens Giraffe
[3466] = { "жевра-бахмат" }, -- Zhevra Courser
[3468] = { "древній знань" }, -- Ancient of Lore
[3469] = { "древній війни" }, -- Ancient of War
[3988] = { "оператор ТзНБ \"Авантюра\"" }, -- Venture Co. Operator
[3989] = { "лісоруб ТзНБ \"Авантюра\"" }, -- Venture Co. Logger
[3991] = { "лісозаготівельник ТзНБ \"Авантюра\"" }, -- Venture Co. Deforester
[3992] = { "інженер ТзНБ \"Авантюра\"" }, -- Venture Co. Engineer
[3993] = { "механік ТзНБ \"Авантюра\"" }, -- Venture Co. Machine Smith
[4064] = { "розвідник Чорнокаменю" }, -- Blackrock Scout
[4065] = { "караульний Чорнокаменю" }, -- Blackrock Sentry
[4111] = { "жорствопикий кобольд" }, -- Gravelsnout Kobold
[4112] = { "жорствопикий шкідник" }, -- Gravelsnout Vermin
[4113] = { "жорствопикий копач" }, -- Gravelsnout Digger
[4114] = { "жорствопикий здобувач" }, -- Gravelsnout Forager
[4116] = { "жорствопикий землемір" }, -- Gravelsnout Surveyor
[4462] = { "мисливець Чорнокаменю" }, -- Blackrock Hunter
[4463] = { "закликач Чорнокаменю" }, -- Blackrock Summoner
[4464] = { "гладіатор Чорнокаменю" }, -- Blackrock Gladiator
[4465] = { "воїн Миршавого Гілля" }, -- Vilebranch Warrior
[4466] = { "скальпоріз Миршавого Гілля" }, -- Vilebranch Scalper
[4467] = { "віщун Миршавого Гілля" }, -- Vilebranch Soothsayer
[4541] = { "кров Аґамаґґана" }, -- Blood of Agamaggan
[4632] = { "колкарський кентавр" }, -- Kolkar Centaur
[4633] = { "колкарський розвідник" }, -- Kolkar Scout
[4634] = { "колкарський молотобій" }, -- Kolkar Mauler
[4635] = { "колкарська вітроловка" }, -- Kolkar Windchaser
[4636] = { "колкарський бойовий лорд" }, -- Kolkar Battle Lord
[4637] = { "колкарський винищувач" }, -- Kolkar Destroyer
[4638] = { "маґрамський розвідник" }, -- Magram Scout
[4639] = { "маґрамський вістовий" }, -- Magram Outrunner
[4640] = { "маґрамський чередник" }, -- Magram Wrangler
[4641] = { "маґрамська вітроловка" }, -- Magram Windchaser
[4642] = { "маґрамська буревійка" }, -- Magram Stormer
[4643] = { "маґрамський чабан" }, -- Magram Pack Runner
[4644] = { "маґрамський мародер" }, -- Magram Marauder
[4645] = { "маґрамський молотобій" }, -- Magram Mauler
[4646] = { "вістовий Ґелкіс" }, -- Gelkis Outrunner
[4647] = { "розвідник Ґелкіс" }, -- Gelkis Scout
[4648] = { "татуювальник Ґелкіс" }, -- Gelkis Stamper
[4649] = { "вітроловка Ґелкіс" }, -- Gelkis Windchaser
[4651] = { "гукачка землі Ґелкіс" }, -- Gelkis Earthcaller
[4652] = { "молотобій Ґелкіс" }, -- Gelkis Mauler
[4653] = { "мародер Ґелкіс" }, -- Gelkis Marauder
[4654] = { "маравдінський розвідник" }, -- Maraudine Scout
[4655] = { "маравдінський чередник" }, -- Maraudine Wrangler
[4656] = { "маравдінський молотобій" }, -- Maraudine Mauler
[4657] = { "маравдінська вітроловка" }, -- Maraudine Windchaser
[4658] = { "маравдінська буревійка" }, -- Maraudine Stormer
[4659] = { "маравдінський мародер" }, -- Maraudine Marauder
[4660] = { "маравдінський кістколап" }, -- Maraudine Bonepaw
[5889] = { "плоскогірний дух землі" }, -- Mesa Earth Spirit
[5890] = { "червоноскельний дух землі" }, -- Redrock Earth Spirit
[5891] = { "менший прояв землі" }, -- Minor Manifestation of Earth
[5893] = { "менший прояв вогню" }, -- Minor Manifestation of Fire
[5902] = { "менший прояв повітря" }, -- Minor Manifestation of Air
[5951] = { "заєць" }, -- Hare
[5952] = { "бугай Лігва" }, -- Den Grunt
[5953] = { "бугай Колючого Пагорба" }, -- Razor Hill Grunt
[6020] = { "намулошкура макрура" }, -- Slimeshell Makrura
[6021] = { "дух кнура" }, -- Boar Spirit
[6145] = { "зграйка риб" }, -- School of Fish
[6491] = { "зцілювач духу" }, -- Spirit Healer
[6492] = { "породження з тріщини" }, -- Rift Spawn
[6789] = { "колючкове ведмежа" }, -- Thistle Cub
[7235] = { "містик Кривої Сосни" }, -- Gnarlpine Mystic
[8996] = { "пустотник-посіпака" }, -- Voidwalker Minion
[9158] = { "їздовий кінь (бойовий кінь)" }, -- Riding Horse (Warhorse)
[10556] = { "лінивий наймит" }, -- Lazy Peon
[10996] = { "загиблий герой" }, -- Fallen Hero
[11688] = { "проклятий кентавр" }, -- Cursed Centaur
[11859] = { "вартовий приречення" }, -- Doomguard
[14505] = { "їздовий кінь (жахожеребець)" }, -- Riding Horse (Dreadsteed)
[14565] = { "їздовий кінь (громак)" }, -- Riding Horse (Charger)
[15760] = { "зимній гуляка" }, -- Winter Reveler
[16096] = { "забіяка Паровиманювання" }, -- Steamwheedle Bruiser
[16371] = { "споліморфлена свиня" }, -- Polymorphed Pig
[16372] = { "споліморфлена вівця" }, -- Polymorphed Sheep
[16373] = { "споліморфлений пацюк" }, -- Polymorphed Rat
[16374] = { "споліморфлений тарган" }, -- Polymorphed Cockroach
[16377] = { "споліморфлена черепаха" }, -- Polymorphed Turtle
[16779] = { "споліморфлена корова" }, -- Polymorphed Cow
}
