local _, addonTable = ...
addonTable.object = { -- [key] = text

-- common

["Anvil"] = "ковадло",
["Mailbox"] = "поштова скринька",

-- herbs

["Arthas' Tears"] = "сльози Артаса",
["Black Lotus"] = "чорний лотос",
["Blindweed"] = "сліпниця",
["Briarthorn"] = "шипшилючка",
["Bruiseweed"] = "синцівка",
["Doom Weed"] = "трава приреченості",
["Dreamfoil"] = "снолистя",
["Earthroot"] = "землекорінь",
["Fadeleaf"] = "бляклолист",
["Firebloom"] = "вогнеквіт",
["Ghost Mushroom"] = "примарний гриб",
["Gloom Weed"] = "бур'ян мороку",
["Golden Sansam"] = "золотий сансам",
["Goldthorn"] = "злотошпичка",
["Grave Moss"] = "могильний мох",
["Gromsblood"] = "ґромокров",
["Icecap"] = "льодошапка",
["Khadgar's Whisker"] = "хадґарів вус",
["Kingsblood"] = "королекров",
["Liferoot"] = "життєкорінь",
["Mageroyal"] = "маговелич",
["Mountain Silversage"] = "гірська срібномудриця",
["Peacebloom"] = "мироквіт",
["Plaguebloom"] = "чумоцвіт",
["Purple Lotus"] = "пурпуровий лотос",
["Serpentbloom"] = "змієквітка",
["Silverleaf"] = "срібнолист",
["Stranglekelp"] = "душирість",
["Sungrass"] = "сонцетравка",
["Violet Tragan"] = "фіолетовий траґан",
["Wild Steelbloom"] = "дикий сталецвіт",
["Wintersbite"] = "зимокус",

-- quest

["Ancient Relic"] = "древня реліквія",
["Beached Sea Creature"] = "викинута на берег морська істота",
["Blue Raptor Nest"] = "гніздо блакитного раптора",
["Bloodpetal Sprout"] = "паросток кровоцвіту",
["Bolt Charged Bramble"] = "заряджена блискавкою тростина",
["Cache of Explosives"] = "cховок з вибухівкою",
["Crate of Elunite"] = "ящик елуніту",
["Damaged Crate"] = "пошкоджений ящик",
["Document Chest"] = "скриня для документів",
["Dragonmaw Catapult"] = "катапульта Драконопащих",
["Ebenezer Rustlocke's Corpse"] = "тіло Ебенезера Іржегака",
["Flame of Uzel"] = "полум'я Узела",
["Half-buried Barrel"] = "наполовину зарита бочка",
["Incendia Agave"] = "вогниста агава",
["Intrepid's Locked Strongbox"] = "замкнений сейф на \"Відважному\"",
["Ironband's Strongbox"] = "скриня Залізоплета",
["Loose Soil"] = "пухкий ґрунт",
["Matrix Punchograph 3005-A"] = "матричний перфограф 3005-A",
["Matrix Punchograph 3005-B"] = "матричний перфограф 3005-B",
["Musquash Root"] = "ондатровий корінь",
["Red Raptor Nest"] = "гніздо червоного раптора",
["Sealed Barrel"] = "запечатана бочка",
["Skeletal Sea Turtle"] = "кістяна морська черепаха",
["Stolen Iron Chest"] = "поцуплена залізна скриня",
["Stone of Outer Binding"] = "камінь Зовнішнього Поневолення",
["Tear of Tilloa"] = "сльоза Тіллої",
["Yellow Raptor Nest"] = "гніздо жовтого раптора",

}
