local _, addonTable = ...
addonTable.object = { -- [id] = { title }
-- todo: sort the list of objects
[ "Mailbox" ] = { "Поштова скринька" },
[ "Forge" ] = { "Ковадло" },

[ "Arthas' Tears" ] = { "Сльози Артаса" },
[ "Beached Sea Creature" ] = { "Викинута на Берег Морська Істота" },
[ "Black Lotus" ] = { "Чорний Лотос" },
[ "Blindweed" ] = { "Сліпниця" },
[ "Briarthorn" ] = { "Шипшилючка" },
[ "Bruiseweed" ] = { "Синцівка" },
[ "Doom Weed" ] = { "Трава Приреченості" },
[ "Dreamfoil" ] = { "Снолистя" },
[ "Earthroot" ] = { "Землекорінь" },
[ "Fadeleaf" ] = { "Бляклолист" },
[ "Firebloom" ] = { "Вогнеквіт" },
[ "Ghost Mushroom" ] = { "Примарний Гриб" },
[ "Gloom Weed" ] = { "Бур'ян Мороку" },
[ "Golden Sansam" ] = { "Золотий Сансам" },
[ "Goldthorn" ] = { "Злотошпичка" },
[ "Grave Moss" ] = { "Могильний Мох" },
[ "Gromsblood" ] = { "Ґромокров" },
[ "Icecap" ] = { "Льодошапка" },
[ "Incendia Agave" ] = { "Запальна Агава" },
[ "Khadgar's Whisker" ] = { "Хадґарів Вус" },
[ "Kingsblood" ] = { "Королекров" },
[ "Liferoot" ] = { "Життєкорінь" },
[ "Mageroyal" ] = { "Маговелич" },
[ "Mountain Silversage" ] = { "Гірська Срібномудриця" },
[ "Peacebloom" ] = { "Мироквіт" },
[ "Plaguebloom" ] = { "Чумоцвіт" },
[ "Purple Lotus" ] = { "Пурпуровий Лотос" },
[ "Serpentbloom" ] = { "Змієквітка" },
[ "Silverleaf" ] = { "Срібнолист" },
[ "Skeletal Sea Turtle" ] = { "Кістяна Морська Черепаха" },
[ "Stranglekelp" ] = { "Душирість" },
[ "Sungrass" ] = { "Сонцетравка" },
[ "Violet Tragan" ] = { "Фіолетовий Траґан" },
[ "Wild Steelbloom" ] = { "Дикий Сталецвіт" },
[ "Wintersbite" ] = { "Зимокус" },

[ "Blue Raptor Nest" ] = { "Гніздо Блакитного Раптора" },
[ "Yellow Raptor Nest" ] = { "Гніздо Жовтого Раптора" },
[ "Red Raptor Nest" ] = { "Гніздо Червоного Раптора" },

}
