-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

addonTable.stat_count = {
total = {
    quests = 6428,
    books = 288,
    npcs = 11029,
    items = 22823,
    spells = 12843,
    sod_engravings = 267,
    objects = 1473,
    zones = 3210,
    chats = 372,
    gossips = 7,
    misc = 281,
},
classic = {
    quests = 4275,
    books = 262,
    npcs = 8645,
    items = 15009,
    spells = 6766,
    objects = 1062,
    chats = 319,
    gossips = 7,
},
sod = {
    quests = 916,
    books = 26,
    npcs = 1491,
    items = 6825,
    spells = 3452,
    sod_engravings = 267,
    objects = 260,
    chats = 46,
    gossips = 0,
},
tbc = {
    quests = 966,
    books = 0,
    npcs = 875,
    items = 982,
    spells = 320,
    objects = 151,
    chats = 0,
    gossips = 0,
},
wrath = {
    quests = 271,
    books = 0,
    npcs = 8,
    items = 7,
    spells = 566,
    objects = 0,
    chats = 0,
    gossips = 0,
},
cata = {
    quests = 0,
    books = 0,
    npcs = 10,
    items = 0,
    spells = 1739,
    objects = 0,
    chats = 7,
    gossips = 0,
},
}
