-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

addonTable.stat_count = {
total = {
    quests = 6355,
    books = 285,
    npcs = 10741,
    items = 22273,
    spells = 12705,
    sod_engravings = 267,
    objects = 1459,
    zones = 3168,
    chats = 21,
    gossips = 6,
    misc = 281,
},
classic = {
    quests = 4275,
    books = 262,
    npcs = 8640,
    items = 15009,
    spells = 6765,
    objects = 1056,
    chats = 10,
    gossips = 6,
},
sod = {
    quests = 843,
    books = 23,
    npcs = 1208,
    items = 6275,
    spells = 3315,
    sod_engravings = 267,
    objects = 251,
    chats = 4,
    gossips = 0,
},
tbc = {
    quests = 966,
    books = 0,
    npcs = 875,
    items = 982,
    spells = 320,
    objects = 152,
    chats = 0,
    gossips = 0,
},
wrath = {
    quests = 271,
    books = 0,
    npcs = 8,
    items = 7,
    spells = 566,
    objects = 0,
    chats = 0,
    gossips = 0,
},
cata = {
    quests = 0,
    books = 0,
    npcs = 10,
    items = 0,
    spells = 1739,
    objects = 0,
    chats = 7,
    gossips = 0,
},
}
