-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

addonTable.stat_count = {
total = {
    quests = 6355,
    books = 286,
    npcs = 10747,
    items = 22274,
    spells = 12710,
    sod_engravings = 267,
    objects = 1462,
    zones = 3169,
    chats = 372,
    gossips = 7,
    misc = 281,
},
classic = {
    quests = 4275,
    books = 262,
    npcs = 8644,
    items = 15009,
    spells = 6766,
    objects = 1059,
    chats = 319,
    gossips = 7,
},
sod = {
    quests = 843,
    books = 24,
    npcs = 1210,
    items = 6276,
    spells = 3319,
    sod_engravings = 267,
    objects = 251,
    chats = 46,
    gossips = 0,
},
tbc = {
    quests = 966,
    books = 0,
    npcs = 875,
    items = 982,
    spells = 320,
    objects = 152,
    chats = 0,
    gossips = 0,
},
wrath = {
    quests = 271,
    books = 0,
    npcs = 8,
    items = 7,
    spells = 566,
    objects = 0,
    chats = 0,
    gossips = 0,
},
cata = {
    quests = 0,
    books = 0,
    npcs = 10,
    items = 0,
    spells = 1739,
    objects = 0,
    chats = 7,
    gossips = 0,
},
}
