local _, addonTable = ...
local tbc_zones = { -- [key] = text
["Azuremyst Isle"] = "Острів Лазурової Димки",

["Ammen Fields"] = "Поля Аммен",
["Ammen Ford"] = "Переправа Аммен",
["Ammen Vale"] = "Долина Аммен",
["Azure Watch"] = "Лазурова застава",
["Bristlelimb Village"] = "Поселення Клишоногів",
["Crash Site"] = "Місце Аварії",
["Emberglade"] = "Тліюча Поляна",
["Fairbridge Strand"] = "Узбережжя у Міцного Моста",
["Geezle's Camp"] = "Табір Ґізла",
["Menagerie Wreckage"] = "Залишки Звіринця",
["Moongraze Woods"] = "Ліса Місячного Оленя",
["Moonwing Den"] = "Прихисток Місячних Крил",
["Nestlewood Hills"] = "Совині Пагорби",
["Nestlewood Thicket"] = "Совина Чаща",
["Odesyus' Landing"] = "Табір Одесия",
["Pod Cluster"] = "Відсік Капсули",
["Pod Wreckage"] = "Уламки Капсули",
["The Sacred Grove"] = "Тліюча Поляна",
["Shadow Ridge"] = "Хребет Тіней",
["Silting Shore"] = "Замулене узбережжя",
["Silverline Lake"] = "Озеро Срібляної Димки",
["Silvermyst Isle"] = "Острів Срібляної Димки",
["Stillpine Hold"] = "лігво клану Тихвій",
["Tides' Hollow"] = "Печера Приливів",
["Traitor's Cove"] = "Священний гай",
["Valaar's Berth"] = "Причал Валаара",
["Wildwind Path"] = "Штормовий шлях",
["Wildwind Peak"] = "Штормовий пік",
["Wrathscale Point"] = "Руїни клану Зловісної Луски",


["The Exodar"] = "Екзодар",

["Seat of the Naaru"] = "Трон Наару",
["The Crystal Hall"] = "Кристалевий Зал",
["The Vault of Lights"] = "Чертог Світла",
["Traders' Tier"] = "Торгівельний Ряд",


["Bloodmyst Isle"] = "Острів Кровавої Димки",

["Amberweb Pass"] = "Перевал Бурштинового Павутиння",
["Axxarien"] = "Аксаріен",
["Beryl Coast"] = "Кроваве узбережжя",
["Blacksilt Shore"] = "Узбережжя Чорного Мулу",
["Bladewood"] = "Ліс Клинків",
["Blood Watch"] = "Кровава Застава",
["Bloodcurse Isle"] = "Острів Проклятої Крові",
["The Bloodcursed Reef"] = "Заговорений риф",
["The Bloodwash"] = "Кровавий Прибій",
["Bristlelimb Enclave"] = "Анклав Клишоногів",
["The Crimson Reach"] = "Багряна межа",
["The Cryo-Core"] = "Криогенний блок",
["The Foul Pool"] = "Сморідний ставок",
["The Hidden Reef"] = "Підводний риф",
["Kessel's Crossing"] = "Перехрестя Кессела",
["The Lost Fold"] = "Загублена Падь",
["Middenvale"] = "Пріла долина",
["Mystwood"] = "Таємничий гай",
["Nazzivian"] = "Наззивіан",
["Ragefeather Ridge"] = "Хребет Лютого Пера",
["Ruins of Loreth'Aran"] = "Руїни Лорет'Арана",
["Talon Stand"] = "Пагорб Кігтя",
["Tel'athion's Camp"] = "Табір Тел'атіона",
["The Vector Coil"] = "Енергоблок",
["Veridian Point"] = "Вершина Веридіан",
["Vindicator's Rest"] = "Привал Захисника",
["The Warp Piston"] = "Надприскорювач",
["Wrathscale Lair"] = "Лігво клану Зловісної Луски",
["Wyrmscar Island"] = "Острів Драконової Скорботи",
}

for k, v in pairs(tbc_zones) do addonTable.zone[k] = v end
