-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

addonTable.book = { -- [id] = { page1, page2 (optional), page3 (optional), ... }
}

if addonTable.book then
    for k, v in pairs(book) do addonTable.book[k] = v end
else
    addonTable.book = book
end
