-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local npc = { -- [id] = { title, description (optional) }
[715] = { "Гемет Ернінґвей-молодший", en="Hemet Nesingwary Jr." }, -- Hemet Nesingwary Jr.
[10182] = { "Рокаро", "герой Орди", en="Rokaro" }, -- Rokaro
[16144] = { "лорд Салтеріл" }, -- Saltheril
[16475] = { "Меґелон", en="Megelon" }, -- Megelon
[16477] = { "Проеніт", en="Proenitus" }, -- Proenitus
[17240] = { "адмірал Одессий", "військово-морське командування Альянсу", en="Admiral Odesyus" }, -- Admiral Odesyus
[17318] = { "Ґізл", en="Geezle" }, -- Geezle
[17359] = { "Тел'атіон Нечистий" }, -- Tel'athion
[17649] = { "Кессел", "повелитель елекків", en="Kessel" }, -- Kessel
[20112] = { "вітряний торговець Тулуман", "продавець зброї" }, -- Tuluman <Weapon Merchant>
[20132] = { "Сокретар", en="Socrethar" }, -- Socrethar
[20284] = { "Доктор Бум", en="Dr. Boom" }, -- Dr. Boom
[21057] = { "принц сплетіння Разаан" }, -- Razaan
[21691] = { "Тошлі", en="Toshley" }, -- Toshley
[21699] = { "Маєв Пісня Тіней", en="Maiev Shadowsong" }, -- Maiev Shadowsong
[23061] = { "Чорнодер", en="Rivendark" }, -- Rivendark
[23230] = { "Шартуул", en="Shartuul" }, -- Shartuul
[23261] = { "Лютокрила", en="Furywing" }, -- Furywing
[23281] = { "Інсідій", en="Insidion" }, -- Insidion
[23282] = { "Обсідія", en="Obsidia" }, -- Obsidia
[23391] = { "Баш'ір", en="Bash'ir" }, -- Bash'ir
[23841] = { "Гостроспин", en="Razorspine" }, -- Razorspine
[23951] = { "лейтенант Аден", en="Lieutenant Aden" }, -- Lieutenant Aden
[23979] = { "гігантська болотна жаба", en="Giant Marsh Frog" }, -- Giant Marsh Frog
}

if addonTable.npc then
    for k, v in pairs(npc) do addonTable.npc[k] = v end
else
    addonTable.npc = npc
end
