-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local chat = { -- [npc_name_en] = { [1] = npc_name_uk (optional), [hash]=translation, ..., [!code]={ [code]=hash, ...} (optional) }
["!player"] = {
-- Excellent!
[3067708623] = [===[Блискуче!]===],
},
["Assistant Greely"] = {
-- Greely coughs.
[2440344171] = [===[Грілі кашляє.]===],
-- Greely sighs and rolls her eyes.
[659597168] = [===[Грілі зітхає і закочує очі.]===],
-- Is that egg on your face?
[2442827493] = [===[Це що, яйце, на вашому обличчі?]===],
-- It's the one on the far right! Hurry, Hobart! It's going to eggsplode!
[1780441515] = [===[Це той що крайній праворуч! Покваптеся, Гобарте! Воно от-от яйцебухне!]===],
-- Now what's this about you 'always loved me', Grapplehammer?
[1443819055] = [===[І що це було про 'завжди любили мене', Грейфомолоте?]===],
-- The assistant shakes her head.
[135724063] = [===[Асистентка хитає головою.]===],
-- There. One Micro Mechachicken. I'll never understand how you come up with these names.
[3193573617] = [===[Ось, одне мікро-меха-курча. Мабуть, ніколи не збагну, звідки ви берете ці назви.]===],
-- Um, Hobart, you're at the controls.
[3961795584] = [===[Гм, Гобарте, ви поряд із панеллю керування.]===],
-- WHAT?!!!
[2344547347] = [===[ЩО?!!!]===],
-- We can both agree on that, doctor.
[2070209616] = [===[В цьому наші думки збігаються, докторе.]===],
-- We're still alive, Doctor Grapplehammer, despite your best efforts.
[1675674026] = [===[Ми досі живі, докторе Грейфомолоте, попри всі ваші потуги.]===],
-- Ya think? Hobart, the Micro Mechachicken is destablizing. It's expanding!
[2277276506] = [===[Думаєте? Гобарте, мікро-меха-курча дестабілізується. Воно збільшується!]===],
-- Yes, Doctor Grapplehammer.
[2381483598] = [===[Так, докторе Грейфомолоте.]===],
-- You don't have to yell, Hobart, I'm standing right here. Sheesh!
[980960439] = [===[Не треба кричати, Гобарте, я стою поряд. Шііш!]===],
},
["Hobart Grapplehammer"] = {
-- Are we still alive?
[1511179017] = [===[Ми досі живі?]===],
-- Excellent. Now back away from the Ultra Concave Fissionable Testing Platform. Slowly, if you please.
[2456318324] = [===[Чудово. А тепер відійди від ультраввігнутої розщеплювальної платформи для тестування. Повільно, будь ласка.]===],
-- Flip the switch!
[1818297637] = [===[Активуй перемикач!]===],
-- Flipping the override switch now!
[1962644749] = [===[Вже активую перемикач відміни!]===],
-- Greely, can you feel it? My moment of success is at hand!
[4223855671] = [===[Грілі, ти це відчуваєш? Мій момент успіху наближається!]===],
-- Grocery store owners everywhere will owe me a percentage of their profits!
[564016127] = [===[Власники продуктових крамниць скрізь будуть винні мені відсоток від свого прибутку!]===],
-- Here goes nothing. I always loved you, Greely!
[4066329719] = [===[Ось і все. Я завжди любив тебе, Грілі!]===],
-- Hobart's jaw hits the ground.
[3309512043] = [===[Щелепа Гобарта падає на підлогу.]===],
-- I am going to end the horrible problem of food storage cutting into the profits of the Bilgewater Cartel!
[1547738648] = [===[Я збираюся покінчити з жахливою проблемою зберігання продуктів, що скорочує прибутки картелю Трюмної води!]===],
-- I am now flipping the switch!
[2623939748] = [===[Я активую перемикач!]===],
-- I haven't the foggiest notion what you're talking about, Miss Greely.
[3537273234] = [===[Я не маю навіть віддаленого уявлення, про що ви говорите, міс Грілі.]===],
-- I know... I know! Where's the override? The override?!
[841464414] = [===[Я знаю... я знаю! Де вимикач? Вимикач?!]===],
-- I'll soon be revered as the greatest goblin tinker of all time! Besides, that negligence case involving the creation of the gilgoblins will never stick.
[2272647380] = [===[Невдовзі мене шануватимуть як найкращого гобліна-штукаря усіх часів! Крім того, та необачна справа, пов'язана зі створенням гіл-гоблінів, ніколи не закріпиться.]===],
-- I'm flipping the second switch!
[2360751917] = [===[Я активую другий перемикач!]===],
-- Prepare the Micro Mechachicken!
[1045763301] = [===[Підготуйте мікро-меха-курча!]===],
-- Quite right, Greely. You passed today's pop quiz.
[3720955135] = [===[Цілком вірно, Грілі. Ти пройшла сьогоднішню перевірку.]===],
-- Thank you. Now behold as I stabilize the highly unstable miniaturization process.
[1232041279] = [===[Дякую. Тепер дивись, як я стабілізую високонестабільний процес мініатюризації.]===],
-- There's a great deal that you do not understand, my dear Greely. That is why you are the assistant and I... I am Hobart Grapplehammer!
[3301369935] = [===[Ти багато чого не розумієш, люба Ґрілі. Ось чому ти асистентка, а я... я — Гобарт Грейфомолот!]===],
-- Wait... something's wrong!
[3710776011] = [===[Зажди... щось не так!]===],
-- Well of course we are, my dear Greely. And look there. The Micro Mechachicken's stabilization appears to be a complete success!
[3913401521] = [===[Ну, звичайно, живі, люба Ґрілі. І поглянь, здається, стабілізація мікро-меха-курчати завершилася успішно!]===],
},
["Kaja'Cola Balloon"] = {
-- Drink Kaja'Cola!
[2671472329] = [===[Пий Каджа-Колу!]===],
-- Enjoy the refreshingly intelligent taste of all new Kaja'Cola!
[1679002954] = [===[Насолоджуйтеся освіжаючим інтелектуальним смаком нової Каджа-Коли!]===],
-- Kaja'Cola is a proud sponsor of the Bilgewater Buccaneers!
[711165583] = [===[Каджа-Кола — гордий спонсор піратів Трюмної води!]===],
-- Kaja'Cola! It gives you IDEAS!
[3639300339] = [===[Каджа-Кола! Наповнює вас ІДЕЯМИ!]===],
-- Kaja'Cola! Jinxy the Weasel says, Drink it... or else!
[1277917496] = [===[Каджа-Кола! Джинксі-Ласка говорить, пийте... або ще!]===],
-- Kaja'Cola! When your tinkering has to be second to none!
[2416250305] = [===[Каджа-Кола! Коли ваша майстерність має бути неперевершеною!]===],
-- Take the Kaja'Cola Taste Test Challenge!
[1762935399] = [===[Прийміть виклик випробування смаку Каджа-Коли!]===],
},
["Maxx Avalanche"] = {
-- Shadow and fire, how quaint. Ride the lightning!
[3442023235] = [===[Тінь та вогонь, як оригінально. Осідлай блискавку!]===],
},
["Sassy Hardwrench"] = {
-- Haha! That should be a blast!
[3887724747] = [===[Ха-ха! Має бути вибухово!]===],
},
["Sister Goldskimmer"] = {
-- Hope you don't mind the extra fortitude, <boss-man/boss-lady>.
[354775951] = [===[Сподіваюся, ви не проти додаткової стійкості, {стать:пане-бос:пані-бос}.]===],
-- I really should charge you for that.
[1786184250] = [===[Мені вже час брати з вас гроші.]===],
-- I was wondering when I'd see you again, <name>.
[3438828945] = [===[Мені все було цікаво, коли ж я побачу вас знову, {ім'я:к}.#again, <name>.]===],
-- It's not much, but it just might keep your green hide intact.
[2482704786] = [===[Це небагато, але може вберегти вашу зелену шкуру неушкодженою.]===],
-- Just wanted to let you know that we're all counting on you!
[3660468543] = [===[Просто хотіла сказати, ми всі розраховуємо на вас!]===],
-- Light be with you... for the very low price of a one silver tithe!
[3158017102] = [===[Світло з вами... за дуже низьку ціну, за крихту срібла!]===],
-- Nothing wrong with a little drive-by fortitude!
[3314228777] = [===[Нічого поганого в невеликій прибавці до стійкості!]===],
-- That one's free of charge, <sir/ma'am>.
[1366712352] = [===[Це безкоштовно, {стать:пане:пані}.]===],
["!code"] = {
["heyudtmdteeafeb."] = 354775951,
["wswgwnidseyuan.-"] = 3438828945,
["ttosfeofce.."] = 1366712352,
},
},
}

if addonTable.chat then
    for k, v in pairs(chat) do
        if type(addonTable.chat[k]) == "table" and type(v) == "table" then
            for vk, vv in pairs(v) do
                addonTable.chat[k][vk] = vv
            end
        else
            addonTable.chat[k] = v
        end
    end
else
    addonTable.chat = chat
end
