-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local chat = { -- [npc_name_en] = { [1] = npc_name_uk (optional), [code1] = text1, [code2] = text2, ... }
["!player"] = {
-- Excellent!
["excellent_"] = [===[Блискуче!]===],
},
["Assistant Greely"] = {
-- Greely coughs.
["gceelycoug"] = [===[Грілі кашляє.]===],
-- Greely sighs and rolls her eyes.
["gsarhesigh"] = [===[Грілі зітхає і закочує очі.]===],
-- It's the one on the far right! Hurry, Hobart! It's going to eggsplode!
["iisgtefrhh"] = [===[Це той що крайній праворуч! Покваптеся, Гобарте! Воно от-от яйцебухне!]===],
-- Is that egg on your face?
["iteoyfeggo"] = [===[Це що, яйце, на вашому обличчі?]===],
-- Now what's this about you 'always loved me', Grapplehammer?
["nwstayalmg"] = [===[І що це було про 'завжди любили мене', Грейфомолоте?]===],
-- The assistant shakes her head.
["tashhsista"] = [===[Асистентка хитає головою.]===],
-- There. One Micro Mechachicken. I'll never understand how you come up with these names.
["tcuwtnnuhy"] = [===[Ось, одне мікро-меха-курча. Мабуть, ніколи не збагну, звідки ви берете ці назви.]===],
-- Um, Hobart, you're at the controls.
["uhyratctyo"] = [===[Гм, Гобарте, ви поряд із панеллю керування.]===],
-- We can both agree on that, doctor.
["wcbaotdtha"] = [===[В цьому наші думки збігаються, докторе.]===],
-- WHAT?!!!
["what______"] = [===[ЩО?!!!]===],
-- We're still alive, Doctor Grapplehammer, despite your best efforts.
["wrsadgdybe"] = [===[Ми досі живі, докторе Грейфомолоте, попри всі ваші потуги.]===],
-- Yes, Doctor Grapplehammer.
["ydgdoctorg"] = [===[Так, докторе Грейфомолоте.]===],
-- Ya think? Hobart, the Micro Mechachicken is destablizing. It's expanding!
["yehtmmidis"] = [===[Думаєте? Гобарте, мікро-меха-курча дестабілізується. Воно збільшується!]===],
-- You don't have to yell, Hobart, I'm standing right here. Sheesh!
["yrhstyhims"] = [===[Не треба кричати, Гобарте, я стою поряд. Шііш!]===],
},
["Hobart Grapplehammer"] = {
-- Are we still alive?
["awsaestill"] = [===[Ми досі живі?]===],
-- Excellent. Now back away from the Ultra Concave Fissionable Testing Platform. Slowly, if you please.
["epsiypucft"] = [===[Чудово. А тепер відійди від ультраввігнутої розщеплювальної платформи для тестування. Повільно, будь ласка.]===],
-- Flipping the override switch now!
["ftosningth"] = [===[Вже активую перемикач відміни!]===],
-- Flip the switch!
["ftsptheswi"] = [===[Активуй перемикач!]===],
-- Greely, can you feel it? My moment of success is at hand!
["gahfimmosi"] = [===[Грілі, ти це відчуваєш? Мій момент успіху наближається!]===],
-- Grocery store owners everywhere will owe me a percentage of their profits!
["gtpewomapo"] = [===[Власники продуктових крамниць скрізь будуть винні мені відсоток від свого прибутку!]===],
-- Here goes nothing. I always loved you, Greely!
["hgnialygno"] = [===[Ось і все. Я завжди любив тебе, Грілі!]===],
-- Hobart's jaw hits the ground.
["hsjhtgsjaw"] = [===[Щелепа Гобарта падає на підлогу.]===],
-- I haven't the foggiest notion what you're talking about, Miss Greely.
["iamgfnwyrt"] = [===[Я не маю навіть віддаленого уявлення, про що ви говорите, міс Грілі.]===],
-- I am now flipping the switch!
["ianftsflip"] = [===[Я активую перемикач!]===],
-- I know... I know! Where's the override? The override?!
["ikikwstoto"] = [===[Я знаю... я знаю! Де вимикач? Вимикач?!]===],
-- I'm flipping the second switch!
["imftssping"] = [===[Я активую другий перемикач!]===],
-- I'll soon be revered as the greatest goblin tinker of all time! Besides, that negligence case involving the creation of the gilgoblins will never stick.
["iocotgwnst"] = [===[Невдовзі мене шануватимуть як найкращого гобліна-штукаря усіх часів! Крім того, та необачна справа, пов'язана зі створенням гіл-гоблінів, ніколи не закріпиться.]===],
-- I am going to end the horrible problem of food storage cutting into the profits of the Bilgewater Cartel!
["iscitpotbc"] = [===[Я збираюся покінчити з жахливою проблемою зберігання продуктів, що скорочує прибутки картелю Трюмної води!]===],
-- Prepare the Micro Mechachicken!
["ptmmarethe"] = [===[Підготуйте мікро-меха-курча!]===],
-- Quite right, Greely. You passed today's pop quiz.
["qrgyptspqt"] = [===[Цілком вірно, Грілі. Ти пройшла сьогоднішню перевірку.]===],
-- There's a great deal that you do not understand, my dear Greely. That is why you are the assistant and I... I am Hobart Grapplehammer!
["tmaaiiahgt"] = [===[Ти багато чого не розумієш, люба Ґрілі. Ось чому ти асистентка, а я... я — Гобарт Грейфомолот!]===],
-- Thank you. Now behold as I stabilize the highly unstable miniaturization process.
["tmpbaisthu"] = [===[Дякую. Тепер дивись, як я стабілізую високонестабільний процес мініатюризації.]===],
-- Wait... something's wrong!
["wsswsometh"] = [===[Зажди... щось не так!]===],
-- Well of course we are, my dear Greely. And look there. The Micro Mechachicken's stabilization appears to be a complete success!
["wtacsssatb"] = [===[Ну, звичайно, живі, люба Ґрілі. І поглянь, здається, стабілізація мікро-меха-курчати завершилася успішно!]===],
},
["Kaja'Cola Balloon"] = {
-- Drink Kaja'Cola!
["dkcnkkajac"] = [===[Пий Каджа-Колу!]===],
-- Enjoy the refreshingly intelligent taste of all new Kaja'Cola!
["etritoankc"] = [===[Насолоджуйтеся освіжаючим інтелектуальним смаком нової Каджа-Коли!]===],
-- Kaja'Cola is a proud sponsor of the Bilgewater Buccaneers!
["kciapsotbb"] = [===[Каджа-Кола — гордий спонсор піратів Трюмної води!]===],
-- Kaja'Cola! It gives you IDEAS!
["kcigyilait"] = [===[Каджа-Кола! Наповнює вас ІДЕЯМИ!]===],
-- Kaja'Cola! Jinxy the Weasel says, Drink it... or else!
["kcjtwsdioe"] = [===[Каджа-Кола! Джинксі-Ласка говорить, пийте... або ще!]===],
-- Kaja'Cola! When your tinkering has to be second to none!
["knwythtbst"] = [===[Каджа-Кола! Коли ваша майстерність має бути неперевершеною!]===],
-- Take the Kaja'Cola Taste Test Challenge!
["ttkcttckaj"] = [===[Прийміть виклик випробування смаку Каджа-Коли!]===],
},
["Maxx Avalanche"] = {
-- Shadow and fire, how quaint. Ride the lightning!
["safhqrtldf"] = [===[Тінь та вогонь, як оригінально. Осідлай блискавку!]===],
},
["Sassy Hardwrench"] = {
-- Haha! That should be a blast!
["htsbabatsh"] = [===[Ха-ха! Має бути вибухово!]===],
},
["Sister Goldskimmer"] = {
-- Hope you don't mind the extra fortitude, boss-lady.
["hydtmtefbl"] = [===[Сподіваюся, ви не проти додаткової стійкості, {стать:пане-бос:пані-бос}.]===],
-- It's not much, but it just might keep your green hide intact.
["ighibijmky"] = [===[Це небагато, але може вберегти вашу зелену шкуру неушкодженою.]===],
-- I really should charge you for that.
["irscyftsho"] = [===[Мені вже час брати з вас гроші.]===],
-- I was wondering when I'd see you again, Tarilka.
["iwwwidsyat"] = [===[Мені було цікаво, коли ж знову побачу вас, {ім'я}.]===],
-- Just wanted to let you know that we're all counting on you!
["jcoyyktwra"] = [===[Просто хотіла сказати, ми всі розраховуємо на вас!]===],
-- Light be with you... for the very low price of a one silver tithe!
["laosttvlpo"] = [===[Світло з вами... за дуже низьку ціну, за крихту срібла!]===],
-- Nothing wrong with a little drive-by fortitude!
["nwwaldbfro"] = [===[Нічого поганого в невеликій прибавці до стійкості!]===],
-- That one's free of charge, ma'am.
["tosfocmafr"] = [===[Це безкоштовно, {стать:пане:пані}.]===],
},
}

if addonTable.chat then
    for k, v in pairs(chat) do
        if type(addonTable.chat[k]) == "table" and type(v) == "table" then
            for vk, vv in pairs(v) do
                addonTable.chat[k][vk] = vv
            end
        else
            addonTable.chat[k] = v
        end
    end
else
    addonTable.chat = chat
end
