-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local quest_horde = {
}

if addonTable.quest_horde then
    for k, v in pairs(quest_horde) do addonTable.quest_horde[k] = v end
else
    addonTable.quest_horde = quest_horde
end
