-- -------------------------------- --
-- AUTOGENERATED FILE. DO NOT EDIT. --
-- -------------------------------- --

local _, addonTable = ...

local quest_alliance = {
}

if addonTable.quest_alliance then
    for k, v in pairs(quest_alliance) do addonTable.quest_alliance[k] = v end
else
    addonTable.quest_alliance = quest_alliance
end
